// Auto-generated by scripts/gen-blog-index-data.mjs
// Do not edit manually. Regenerate with: npm run seo:blog-index-data

export const blogIndexPosts = [
  {
    "slug": "google-ads-za-privatne-skole-cena-upisa-srbija-2026",
    "title": "Google Ads za privatne skole u Srbiji 2026: cena lead-a, budzet i vise upisa",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za privatne skole u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu kvalifikovanog upita bez praznih prijava.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-privatne-vrtice-cena-upisa-srbija-2026",
    "title": "Instagram reklame za privatne vrtice u Srbiji 2026: cena upisa i budzet",
    "excerpt": "Koliko realno kostaju Instagram reklame za privatne vrtice u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalitetne prijave bez praznih poruka.",
    "date": "2026-03-14",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-veterinarske-ambulante-cena-leada-srbija-2026",
    "title": "Google Ads za veterinarske ambulante u Srbiji 2026: cena lead-a, budzet i vise pregleda",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za veterinarske ambulante u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalifikovanog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-teretane-i-fitnes-studije-cena-leada-srbija-2026",
    "title": "Google Ads za teretane i fitnes studije u Srbiji 2026: cena lead-a i budzet",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za teretane i fitnes studije u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu kvalitetne prijave.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-domove-za-stare-cena-leada-srbija-2026",
    "title": "Google Ads za domove za stare u Srbiji 2026: cena lead-a, budzet i vise ozbiljnih prijava",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za domove za stare u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalifikovanog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-agencije-za-nekretnine-cena-leada-srbija-2026",
    "title": "Google Ads za agencije za nekretnine u Srbiji 2026: cena lead-a, budzet i vise ozbiljnih kupaca",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za agencije za nekretnine u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu ozbiljnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-privatne-vrtice-cena-upisa-srbija-2026",
    "title": "Google Ads za privatne vrtice u Srbiji 2026: cena upisa, budzet i vise kvalifikovanih prijava",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za privatne vrtice u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetne prijave bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-salone-namestaja-cena-leada-srbija-2026",
    "title": "Google Ads za salone namestaja u Srbiji 2026: cena lead-a, budzet i vise kupaca",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za salone namestaja u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu kvalitetnog upita bez praznih klikova.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-skolice-stranih-jezika-cena-upisa-srbija-2026",
    "title": "Google Ads za skolice stranih jezika u Srbiji 2026: cena upisa, budzet i manje praznih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za skolice stranih jezika u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog upisa bez praznih prijava.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-autoskole-cena-upisa-srbija-2026",
    "title": "Google Ads za auto skole u Srbiji 2026: cena upisa, budzet i manje praznih poziva",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za auto skole u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog upisa bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-firme-za-selidbe-cena-poziva-srbija-2026",
    "title": "Google Ads za firme za selidbe u Srbiji 2026: cena poziva, budzet i manje izgubljenih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za firme za selidbe u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog poziva bez praznih voznji.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-privatne-klinike-cena-leada-srbija-2026",
    "title": "Google Ads za privatne klinike u Srbiji 2026: cena lead-a, budzet i manje praznih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za privatne klinike u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustis cenu kvalitetnog medicinskog upita.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "redizajn-wordpress-sajta-cena-srbija-2026",
    "title": "Redizajn WordPress sajta cena u Srbiji 2026: sta podize trosak i kako da izbegnes SEO pad",
    "excerpt": "Koliko realno kosta redizajn WordPress sajta u Srbiji 2026, sta najvise podize cenu i kako da uradis vizuelno osvezenje bez pada SEO pozicija i leadova.",
    "date": "2026-03-14",
    "category": "WordPress",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-knjigovodstvene-agencije-cena-leada-srbija-2026",
    "title": "Google Ads za knjigovodstvene agencije u Srbiji 2026: cena lead-a i profitabilan budzet",
    "excerpt": "Koliko kostaju Google Ads kampanje za knjigovodstvene agencije u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu kvalifikovanog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "facebook-reklame-za-stomatologe-cena-termina-srbija-2026",
    "title": "Facebook reklame za stomatologe u Srbiji 2026: cena termina i budzet",
    "excerpt": "Koliko realno kostaju Facebook reklame za stomatoloske ordinacije u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu zakazanog termina bez praznih leadova.",
    "date": "2026-03-14",
    "category": "Facebook Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-bravare-cena-leada-srbija-2026",
    "title": "Google Ads za bravare u Srbiji 2026: cena lead-a, budzet i vise hitnih poziva",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za bravare u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu kvalitetnog upita bez izgubljenih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-elektricare-cena-leada-srbija-2026",
    "title": "Google Ads za elektricare u Srbiji 2026: cena lead-a, budzet i vise hitnih intervencija",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za elektricare u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-keramicare-cena-leada-srbija-2026",
    "title": "Google Ads za keramicare u Srbiji 2026: cena lead-a, budzet i vise kvalitetnih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za keramicare u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjis cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-klima-servis-cena-leada-srbija-2026",
    "title": "Google Ads za klima servis u Srbiji 2026: cena lead-a, sezona i profitabilan raspored budzeta",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za klima servis u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stolare-cena-leada-srbija-2026",
    "title": "Google Ads za stolare u Srbiji 2026: cena lead-a, budzet i vise upita za namestaj po meri",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za stolare u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-13",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "migracija-sajta-na-wordpress-cena-srbija-2026",
    "title": "Migracija sajta na WordPress cena u Srbiji 2026: troskovi, rizici i SEO-safe plan",
    "excerpt": "Koliko realno kosta migracija sajta na WordPress u Srbiji 2026, sta najcesce podize cenu i kako da prebacis sajt bez pada pozicija, leadova i prodaje.",
    "date": "2026-03-13",
    "category": "WordPress",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "seo-optimizacija-wordpress-sajta-cena-srbija-2026",
    "title": "SEO optimizacija WordPress sajta cena u Srbiji 2026: sta ulazi i kako birati ponudu",
    "excerpt": "Koliko realno kosta SEO optimizacija WordPress sajta u Srbiji 2026, sta mora da bude ukljuceno u uslugu i kako da procenis da li ponuda donosi rast ili samo izvestaje.",
    "date": "2026-03-13",
    "category": "WordPress SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-reklame-za-vodoinstalatere-cena-leada-srbija-2026",
    "title": "Google reklame za vodoinstalatere u Srbiji 2026: cena leada, budzet i kako da telefon zvoni",
    "excerpt": "Koliko realno kostaju Google reklame za vodoinstalatere u Srbiji 2026, koji budzet ima smisla i kako da smanjite cenu upita bez gubitka kvaliteta poziva.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-reklame-za-gradjevinske-firme-cena-leada-srbija-2026",
    "title": "Google reklame za gradjevinske firme u Srbiji 2026: cena leada, budzet i profit po projektu",
    "excerpt": "Koliko realno kostaju Google reklame za gradjevinske firme u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu upita bez losih leadova.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-advokate-cena-srbija-2026",
    "title": "SEO za advokate u Srbiji 2026: cena, rokovi i kako da dobijete vise kvalitetnih upita",
    "excerpt": "Koliko realno kosta SEO za advokatske kancelarije u Srbiji 2026, sta ulazi u cenu i kako da merite rezultat kroz kvalitetne pravne upite, a ne samo pozicije.",
    "date": "2026-03-12",
    "category": "Lokalni SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-autoservise-cena-upita-srbija-2026",
    "title": "Instagram reklame za autoservise u Srbiji 2026: cena upita i budzet",
    "excerpt": "Praktican vodic za autoservise: koliki Instagram budzet ima smisla, kako da merite cenu upita i koje kreativne poruke najbrze pune raspored termina.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-ads-cena-po-kliku-srbija-2026",
    "title": "Instagram Ads cena po kliku u Srbiji 2026: realni CPC rasponi i kako da spustis trosak leada",
    "excerpt": "Praktican vodiÄ za Instagram Ads CPC u Srbiji 2026: rasponi po niÅ¡i, glavni razlozi visokog klika i konkretni potezi za niÅ¾i troÅ¡ak uz bolji kvalitet upita.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "izrada-wordpress-sajta-cena-po-tipu-biznisa-srbija-2026",
    "title": "Izrada WordPress sajta cena po tipu biznisa u Srbiji 2026: realni rasponi i sta ulazi u cenu",
    "excerpt": "Koliko realno kosta WordPress sajt u Srbiji 2026 za usluzni biznis, ordinaciju, web shop ili B2B firmu i kako da procenis da li ponuda stvarno ima smisla.",
    "date": "2026-03-12",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "meta-ads-cena-po-kliku-srbija-2026",
    "title": "Meta Ads cena po kliku u Srbiji 2026: realni CPC rasponi i kako da spustis cenu upita",
    "excerpt": "Koliko Meta Ads klik realno kosta u Srbiji 2026 po industriji, gde kampanje najcesce gube budzet i kako da smanjis CPC bez pada kvaliteta leadova.",
    "date": "2026-03-12",
    "category": "Meta Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-onboarding-sistem-zadrzavanje-klijenata-srbija-2026",
    "title": "Leila Hormozi onboarding sistem: kako da zadrzis klijente u marketing agenciji (Srbija 2026)",
    "excerpt": "Praktican onboarding framework za agencije u Srbiji: kako da u prvih 30 dana klijent vidi progres, smanjis churn i podignes LTV bez dizanja ad budzeta.",
    "date": "2026-03-12",
    "category": "Agency Growth",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-7-hour-followup-sistem-srbija-2026",
    "title": "Sabri Suby 7-hour follow-up sistem: kako da ne gubis leadove u Srbiji 2026",
    "excerpt": "Praktican framework za firme u Srbiji: kako da uvedes brz i strukturiran follow-up koji pretvara vise upita u stvarne klijente bez povecanja ad budzeta.",
    "date": "2026-03-12",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-kozmeticki-salon-cena-termina-srbija-2026",
    "title": "Google Ads za kozmeticki salon u Srbiji 2026: cena termina i realan budzet",
    "excerpt": "Praktican vodic za vlasnice kozmetickih salona: koliko kosta Google Ads u Srbiji 2026, koji budzet ima smisla i kako da merite cenu zakazanog termina umesto praznih klikova.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-advokate-cena-klijenta-srbija-2026",
    "title": "Instagram reklame za advokate u Srbiji 2026: cena klijenta i budzet",
    "excerpt": "Koliko realno kostaju Instagram reklame za advokatske kancelarije u Srbiji 2026, koji budzet ima smisla i kako da izbegnes upite koji ne postaju klijenti.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-autoservise-cena-leada-srbija-2026",
    "title": "Google Ads za autoservise u Srbiji 2026: cena leada, budzet i kako da telefon zvoni",
    "excerpt": "Koliko realno kosta Google Ads za auto servis u Srbiji 2026, koji budzet ima smisla za start i kako da spustite cenu upita bez praznih poziva.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-instagram-ads-kampanja-cena-srbija-2026",
    "title": "Vodjenje Instagram Ads kampanja cena u Srbiji 2026: sta realno ulazi u mesecni fee",
    "excerpt": "Koliko kosta vodjenje Instagram Ads kampanja u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li agencijski fee stvarno donosi bolji CPL i veci profit.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "woocommerce-sajt-cena-srbija-2026",
    "title": "WooCommerce sajt cena u Srbiji 2026: koliko realno kosta webshop koji prodaje",
    "excerpt": "Realni rasponi za WooCommerce izradu u Srbiji 2026: sta ulazi u cenu, koji su skriveni troskovi i kako da izbegnes webshop koji izgleda lepo, a ne prodaje.",
    "date": "2026-03-12",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-weekly-scorecard-marketing-srbija-2026",
    "title": "Leila Hormozi weekly scorecard: kako da marketing sistem radi i bez vlasnika (Srbija 2026)",
    "excerpt": "Praktican Leila Hormozi pristup za firme u Srbiji: koje marketing KPI-jeve pratiti svake nedelje, kako postaviti ownership i kada menjati kanal umesto da samo dizete budzet.",
    "date": "2026-03-12",
    "category": "Marketing Strategija",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-stomatologe-cena-termina-srbija-2026",
    "title": "Instagram reklame za stomatologe u Srbiji 2026: cena termina i budzet",
    "excerpt": "Koliki budzet treba ordinaciji za Instagram oglase u Srbiji 2026 i kako da merite cenu zakazanog termina bez praznih leadova.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-restorane-cena-rezervacije-srbija-2026",
    "title": "Instagram reklame za restorane u Srbiji 2026: cena rezervacije i budzet",
    "excerpt": "Koliki budzet ima smisla za Instagram reklame restorana u Srbiji 2026, kako da merite cenu rezervacije i koje poruke najcesce dovode ljude do rezervacije.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-business-profil-za-stomatologe-srbija-2026",
    "title": "Google Business profil za stomatologe u Srbiji 2026: kako do vise poziva i zakazanih termina",
    "excerpt": "Praktican vodic za stomatoloske ordinacije: kako da optimizujete Google Business profil, skupite vise recenzija i pretvorite lokalne pretrage u stvarne pacijente.",
    "date": "2026-03-12",
    "category": "Lokalni SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-b2b-cena-leada-srbija-2026",
    "title": "Google Ads za B2B u Srbiji 2026: cena leada, SQL kvalitet i budzet koji ima smisla",
    "excerpt": "Koliko realno kosta Google Ads za B2B firme u Srbiji 2026, koji CPL raspon ima smisla po niï¿½i i kako da merite SQL kvalitet umesto da jurite jeftine leadove bez pipeline-a.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-ecommerce-cena-prodaje-srbija-2026",
    "title": "Google Ads za e-commerce u Srbiji 2026: cena prodaje, ROAS i budzet bez bacanja para",
    "excerpt": "Koliko realno kosta Google Ads za web shop u Srbiji 2026: CPC, CPA, ROAS, test budzet i koraci kako da skalis samo ono sto je profitabilno.",
    "date": "2026-03-12",
    "category": "E-Commerce",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-advokate-cena-klijenta-srbija-2026",
    "title": "Google Ads za advokate u Srbiji 2026: cena klijenta, budzet i kako da ne bacite novac",
    "excerpt": "Realni CPC/CPL rasponi za advokatske kampanje u Srbiji 2026, koliko budzeta treba za test i kako da merite cenu klijenta umesto cene klika.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-core-4-lead-magnet-srbija-2026",
    "title": "Alex Hormozi Core 4 lead magnet sistem: kako da dobijete vise kvalitetnih upita u Srbiji 2026",
    "excerpt": "Praktican vodic kako da primenis Hormozi Core 4 lead magnet okvir na srpsko trziste i povecas broj kvalitetnih upita bez dupliranja budzeta.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stomatologe-cena-leada-srbija-2026",
    "title": "Google Ads za stomatologe u Srbiji 2026: realna cena leada i kako da ne spalite budzet",
    "excerpt": "Google Ads za stomatologe u Srbiji 2026: realni CPC i CPL rasponi, budzet za start i koraci za vise zakazanih termina.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "facebook-ads-cena-po-industriji-srbija-2026",
    "title": "Facebook Ads cena po industriji u Srbiji 2026: realni CPC/CPL rasponi i budzeti za test",
    "excerpt": "Detaljan vodic za Facebook Ads cenu po industriji u Srbiji 2026: realni rasponi CPC/CPL metrika, starter budzeti i kako da procenis kada kampanja ima zdrav ROI.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "marketing-agencija-cena-srbija-2026",
    "title": "Marketing agencija cena u Srbiji 2026: paketi, rasponi i kako da procenis isplativost",
    "excerpt": "Koliko kosta marketing agencija u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li ponuda donosi profit ili samo aktivnost bez rezultata.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "lead-generation-cena-srbija-2026",
    "title": "Lead generation cena u Srbiji 2026: koliko stvarno kosta kvalitetan upit",
    "excerpt": "Praktican vodic koliko kosta lead generation u Srbiji 2026: realni CPL rasponi, sta podize cenu i kako da razlikujete \"jeftin lead\" od profitabilnog upita.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-seo-cena-zrenjanin-2026",
    "title": "Lokalni SEO cena u Zrenjaninu 2026: koliko koï¿½ta i ï¿½ta realno dobijate",
    "excerpt": "Praktican vodic za lokalni SEO u Zrenjaninu: realni rasponi cena, ï¿½ta mora da ulazi u uslugu i kako da procenite da li ponuda donosi upite ili samo \"aktivnost\".",
    "date": "2026-03-11",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-instagram-profila-cena-srbija-2026",
    "title": "Vodenje Instagram profila cena u Srbiji 2026: ï¿½ta ulazi u paket i koliko je realno",
    "excerpt": "Koliko koï¿½ta vodenje Instagram profila u Srbiji 2026, koje su realne razlike izmedu paketa i kako da izbegnete uslugu koja izgleda jeftino, a ne donosi rezultate.",
    "date": "2026-03-11",
    "category": "Social Media",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-ads-cpc-budzet-plan-srbija-2026",
    "title": "Instagram Ads cena po kliku u Srbiji 2026: realni CPC rasponi i budï¿½et plan",
    "excerpt": "Koliko realno koï¿½ta klik na Instagram oglasima u Srbiji 2026, od cega zavisi CPC i kako da planirate budï¿½et bez skupih greï¿½aka.",
    "date": "2026-03-11",
    "category": "Instagram Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-100m-leads-sistem-za-vise-upita-srbija-2026",
    "title": "Alex Hormozi 100M Leads: sistem za viï¿½e upita bez duplog budï¿½eta (Srbija 2026)",
    "excerpt": "Kako da primeniï¿½ Hormozi 100M Leads pristup na srpsko trï¿½iï¿½te: bolji hook, jasnija ponuda i kvalitetniji leadovi bez bacanja budï¿½eta.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-lokalne-biznise-kako-spustiti-cenu-leada-srbija-2026",
    "title": "Google Ads za lokalne biznise: kako spustiti cenu leada u Srbiji 2026",
    "excerpt": "Praktican vodic za lokalne firme u Srbiji: kako da kroz bolju strukturu kampanje i landing stranicu smanjite cenu upita bez povecanja budï¿½eta.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-value-equation-ponuda-koja-prodaje-srbija-2026",
    "title": "Alex Hormozi Value Equation: kako da ponuda bude skuplja i lakï¿½a za prodaju (Srbija 2026)",
    "excerpt": "Praktican vodic kako da primeniï¿½ Hormozi value equation na usluï¿½ni biznis u Srbiji i podigneï¿½ cenu bez pada konverzije.",
    "date": "2026-03-10",
    "category": "Prodaja",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-cena-po-kliku-srbija-2026",
    "title": "Google Ads cena po kliku u Srbiji 2026: realni CPC rasponi po nisi i intentu",
    "excerpt": "Koliko Google Ads klik realno kosta u Srbiji 2026, koji su rasponi po industrijama i kako da razlikujes zdrav CPC od skupe kampanje koja samo izgleda jeftino.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "12 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-google-ads-kampanja-cena-srbija-2026",
    "title": "Vodenje Google Ads kampanja: cena u Srbiji 2026 (ï¿½ta ulazi u uslugu)",
    "excerpt": "Koliko koï¿½ta vodenje Google Ads kampanja u Srbiji 2026, ï¿½ta ulazi u mesecni fee i kako da procenite da li je ponuda agencije realna ili preskupa.",
    "date": "2026-03-10",
    "category": "Google Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "izrada-landing-stranice-cena-rokovi-sta-ulazi-u-cenu",
    "title": "Izrada landing stranice: cena, rokovi, ï¿½ta ulazi u cenu (Srbija 2026)",
    "excerpt": "Koliko realno kosta landing stranica u Srbiji 2026, sta ulazi u cenu, gde firme najcesce pogrese i kako da procenis da li je ponuda zdrava ili samo izgleda jeftino.",
    "date": "2026-03-11",
    "category": "Web Design",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "copywriting-formule-koje-rade",
    "title": "Kako napisati oglas koji prodaje: copywriting formule koje rade",
    "excerpt": "Nije bitno koliko ljudi vidi vaï¿½ oglas. Bitno je koliko ih ne moï¿½e da odoli a da ne klikne. Evo formula koje to postiï¿½u.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ab-testiranje-male-promene-veliki-rezultati",
    "title": "A/B testiranje: male promene, veliki rezultati",
    "excerpt": "Promena boje dugmeta sama po sebi nece spasiti loï¿½ sajt, ali prava A/B testiranja mogu udvostruciti konverzije kada se testira ponuda, struktura i CTA tok.",
    "date": "2026-02-21",
    "category": "CRO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "kako-meriti-roi-marketinga-kpi-vodic",
    "title": "Kako meriti ROI marketinga: KPI vodic za vlasnike firmi",
    "excerpt": "Ako ne merite marketing, kockate se budï¿½etom. Ovo je 8 kljucnih KPI brojeva koje svaka firma treba da prati da bi znala ï¿½ta donosi profit, a ï¿½ta troï¿½i novac.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "lead-magneti-koji-zapravo-konvertuju",
    "title": "Lead magneti koji zapravo konvertuju",
    "excerpt": "Besplatan PDF koji niko ne preuzme nije lead magnet. Pravi lead magnet pogada tacan problem publike i pretvara posetioce u kvalifikovane upite.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "brending-za-male-firme-identitet-vazniji-od-loga",
    "title": "Brending za male firme: zaï¿½to je identitet vaï¿½niji od loga",
    "excerpt": "Logo je samo pocetak. Brend je utisak koji ljudi pamte. Evo kako male firme grade jasan identitet koji podiï¿½e poverenje, cenu i prodaju.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "video-marketing-zasto-video-dominira",
    "title": "Video marketing: zaï¿½to video dominira i kako poceti",
    "excerpt": "Video cini 82% internet saobracaja. Firme koje ne koriste video gube paï¿½nju publike pre prvog kontakta sa ponudom i ostaju korak iza konkurencije.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "5 min",
    "isDraft": false
  },
  {
    "slug": "seo-vs-ppc-sta-je-bolje-za-dugorocni-rast",
    "title": "SEO vs PPC: ï¿½ta je bolje za dugorocni rast",
    "excerpt": "SEO je maraton, PPC je sprint. Za vecinu firmi najbolji rast dolazi iz pametne kombinacije oba kanala, uz jasan plan budï¿½eta i ciljeva.",
    "date": "2026-02-21",
    "category": "SEO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "psihologija-zaradjivanja-mentalni-blokovi",
    "title": "Psihologija zaradivanja: mentalni blokovi koji koce rast firme",
    "excerpt": "Najveca prepreka rastu cesto nije trï¿½iï¿½te, vec nacin razmiï¿½ljanja vlasnika firme. Evo koji mentalni blokovi koce zaradu i kako da ih razbijete.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "komunikacija-u-prodaji-kako-napisati-ponudu",
    "title": "Komunikacija u prodaji: kako napisati ponudu koja zatvara",
    "excerpt": "Ponude koje se ï¿½alju i zaborave vs ponude nakon kojih klijent pita \"Kad moï¿½emo da pocnemo?\" Razlika je u strukturi.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "kako-izabrati-pravu-marketing-agenciju",
    "title": "Kako izabrati pravu marketing agenciju (i ne baciti novac)",
    "excerpt": "Trï¿½iï¿½te je puno agencija koje obecavaju rezultate. Evo 7 znakova koji razlikuju agencije koje isporucuju od onih koje pricaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "social-proof-recenzije-za-vise-prodaje",
    "title": "Social proof: kako koristiti recenzije za viï¿½e prodaje",
    "excerpt": "92% kupaca cita recenzije pre kupovine. Evo kako da recenzije rade za vas umesto da stoje kao ukras na sajtu i da ih ljudi jedva primete.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "retargeting-zasto-95-posetilaca-ne-kupi",
    "title": "Retargeting: zaï¿½to 95% posetilaca nikad ne kupi iz prvog pokuï¿½aja",
    "excerpt": "Placate saobracaj koji odlazi. Retargeting vraca te ljude po ceni i do 5-10x niï¿½oj od prvog klika i pretvara izgubljene posete u konkretne upite i prodaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "5 min",
    "isDraft": false
  },
  {
    "slug": "customer-retention-zadrzati-vs-naci-novog",
    "title": "Customer retention: zaï¿½to je jeftinije zadrï¿½ati nego naci novog kupca",
    "excerpt": "Novi kupac koï¿½ta 5-7x viï¿½e od zadrï¿½avanja postojeceg. Ovaj vodic pokazuje kako retention strategije povecavaju profit bez dizanja budï¿½eta za akviziciju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "17-godina-marketing-iskustva",
    "title": "17 godina marketing iskustva u jednom tekstu",
    "excerpt": "ï¿½ta se menja u marketingu, a ï¿½ta ostaje isto decenijama? Evo lekcija koje koï¿½taju godine i milione da se nauce.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "13-godina-poslovnog-iskustva-najskuplje-greske",
    "title": "13 godina poslovnog iskustva: najskuplje greï¿½ke koje firme prave",
    "excerpt": "Svaka od ovih greï¿½aka koï¿½ta firme hiljade evra i mesece izgubljenog vremena. Ovo su lekcije iz 13 godina rada koje mogu odmah da vam sacuvaju budï¿½et.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "od-nule-do-prvog-miliona-konkretni-koraci",
    "title": "Od nule do prvog miliona: konkretni koraci za vlasnike firmi",
    "excerpt": "Nema precica, ali postoji redosled koji ï¿½tedi godine lutanja. Ovo su koraci koji najbrï¿½e vode od starta biznisa do prvog miliona prihoda.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-se-kretati-10x-brze-kao-vlasnik-firme",
    "title": "Kako se kretati 10x brï¿½e kao vlasnik firme",
    "excerpt": "Produktivnost nije o tome da radite viï¿½e sati. Produktivnost je o eliminaciji svega ï¿½to ne proizvodi rezultate.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "zasto-vecina-firmi-stagnira-posle-prvog-miliona",
    "title": "Zaï¿½to vecina firmi stagnira posle prvog miliona",
    "excerpt": "Dostizanje prvog miliona zahteva jednu vrstu posla, ali prelazak na sledeci nivo traï¿½i drugaciji sistem, timsku strukturu i disciplinu izvrï¿½enja.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "od-nule-do-prvih-10000-evra-mesecno",
    "title": "Od nule do prvih 10.000 evra mesecno: vodic za pocetnike",
    "excerpt": "Prvih 10.000e mesecno retko dolazi iz talenta. Mnogo cesce dolazi iz nekoliko konkretnih koraka koji mogu da se ponove u skoro svakoj industriji.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "pricing-psihologija-kontrola-percepcije-cene",
    "title": "Pricing psihologija: kako brendovi kontroliï¿½u percepciju cene",
    "excerpt": "Cena nije broj. Cena je prica koju kupac prica sam sebi. Evo kako firme koje naplacuju 10x viï¿½e koriste psihologiju da to opravdaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ponuda-koju-niko-ne-moze-da-odbije",
    "title": "Anatomija neodoljive ponude: zaï¿½to vecina firmi prodaje pogreï¿½no",
    "excerpt": "Vecina firmi se takmici cenom. Firme koje razumeju anatomiju ponude se takmice vrednoï¿½cu. Evo kako napraviti ponudu koja se ne odbija.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "organski-doseg-umire-sta-raditi",
    "title": "Zaï¿½to organski doseg umire i ï¿½ta pametne firme rade umesto toga",
    "excerpt": "Facebook organski doseg pao na 2%. Instagram sledi isti trend. Evo ï¿½ta firme koje i dalje rastu rade drugacije.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-vs-facebook-ads-koji-je-bolji",
    "title": "Google Ads vs Facebook Ads: koji je bolji za vaï¿½ biznis",
    "excerpt": "Google Ads hvata ljude koji aktivno traï¿½e reï¿½enje, Facebook Ads ljude koji tek otkrivaju ponudu. Pravi izbor zavisi od marï¿½e, cilja kampanje i brzine povrata.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "content-marketing-dugorocna-investicija",
    "title": "Content marketing: investicija koja se vraca godinama",
    "excerpt": "Blog post koji ste napisali pre 2 godine i dalje donosi saobracaj. Facebook oglas od pre 2 godine ne donosi niï¿½ta. Evo zaï¿½to je to bitno.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "sales-funnel-koji-radi-na-autopilotu",
    "title": "Kako napraviti sales funnel koji radi dok vi spavate",
    "excerpt": "Dok vi spavate, funnel hvata posetioce, gradi poverenje i zatvara prodaju. Ali samo ako je pravilno napravljen.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-seo-kako-se-pojaviti-prvi",
    "title": "Lokalni SEO: kako se pojaviti prvi kad neko pretraï¿½i u vaï¿½em gradu",
    "excerpt": "Kada neko iz vaseg grada pretrazi uslugu koju nudite, treba da vidi vas pre konkurencije. Evo kako da lokalni SEO to stvarno uradi za vas biznis.",
    "date": "2026-02-20",
    "category": "SEO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "email-marketing-kralj-konverzija",
    "title": "Email marketing: zaï¿½to je email i dalje kralj konverzija",
    "excerpt": "Email marketing i dalje daje vrhunski povrat ulaganja. Saznajte kako e-commerce i usluï¿½ne firme kroz email povecavaju ponovne kupovine i mesecni prihod.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "5-gresaka-landing-stranice-konverzije",
    "title": "5 greï¿½aka na landing stranicama koje ubijaju konverzije",
    "excerpt": "Vecina landing stranica izgubi 90-95% posetilaca bez konverzije. Problem obicno nisu posetilokupci vec dizajn koji sabotira odluku. Evo pet greï¿½aka koje koï¿½taju najviï¿½e.",
    "date": "2026-02-20",
    "category": "CRO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "facebook-oglasi-koji-zapravo-rade",
    "title": "Facebook oglasi koji zapravo rade: psihologija iza klika",
    "excerpt": "Vecina firmi troï¿½i novac na Facebook oglase koji izgledaju kao oglasi. A ljudi mrze oglase. Evo kako napraviti oglas koji izgleda kao sadrï¿½aj i konvertuje kao ludo.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "piramida-kupaca-4-tipa-publike",
    "title": "Piramida kupaca: zaï¿½to vecina firmi gubi 97% trï¿½iï¿½ta",
    "excerpt": "Vecina firmi se bori za isti mali procenat kupaca koji su spremni da kupe odmah. U meduvremenu, ogromna vecina trï¿½iï¿½ta prolazi pored njih nezapaï¿½eno.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "pricing-psihologija-kako-luksuzni-brendovi-kontrolisu-percepciju-cene",
    "title": "Pricing psihologija: kako luksuzni brendovi kontroliï¿½u percepciju cene",
    "excerpt": "Cena nije broj. Cena je prica. Firme koje ovo razumeju ne prodaju jeftinije od konkurencije. Prodaju drugacije.",
    "date": "2026-02-24",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "17-godina-marketing-iskustva-u-jednom-tekstu",
    "title": "17 godina marketing iskustva: lekcije iz jednog teksta",
    "excerpt": "Marketing se menja svake godine. Kanali dolaze i odlaze. Ali principi koji zapravo donose rezultate ostaju isti decenijama.",
    "date": "2026-02-24",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-napraviti-marketing-budzet-koji-ima-smisla",
    "title": "Kako napraviti marketing budï¿½et koji ima smisla",
    "excerpt": "Vecina firmi ili troï¿½i premalo na marketing pa se niï¿½ta ne deï¿½ava, ili troï¿½i bez plana pa ne zna ï¿½ta radi. Evo kako to srediti.",
    "date": "2026-02-24",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ugc-buducnost-oglasa",
    "title": "Zaï¿½to je UGC buducnost oglasa (i kako ga koristiti)",
    "excerpt": "Profesionalni oglasi sve slabije konvertuju. Sadrï¿½aj koji izgleda kao da ga je snimio kupac radi bolje od studijskog materijala.",
    "date": "2026-02-24",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "automatizacija-marketinga-sta-mozete-delegirati-masini",
    "title": "Automatizacija marketinga: ï¿½ta moï¿½ete delegirati maï¿½ini",
    "excerpt": "Neki zadaci troï¿½e sate vaï¿½eg vremena svake nedelje, a mogli bi da se zavrï¿½e bez ijednog klika. Pitanje je samo koje.",
    "date": "2026-02-26",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-biznis-vs-online-hibridna-strategija",
    "title": "Lokalni biznis vs. online: zaï¿½to hibridna strategija pobeduje",
    "excerpt": "Cist online ili cist offline pristup ostavlja novac na stolu. Firme koje kombinuju oba kanala rastu brï¿½e od onih koje biraju stranu.",
    "date": "2026-02-26",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-citati-marketing-izvestaj",
    "title": "Kako citati marketing izveï¿½taj (vodic za vlasnike firmi)",
    "excerpt": "Vecina vlasnika firmi dobije mesecni izveï¿½taj od agencije i ne zna ï¿½ta gleda. Evo ï¿½ta zapravo treba da traï¿½ite u brojevima.",
    "date": "2026-02-26",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "zasto-vas-sajt-ne-prodaje",
    "title": "Zaï¿½to vaï¿½ sajt ne prodaje (i ï¿½ta da promenite danas)",
    "excerpt": "Sajt izgleda lepo, ali telefon ne zvoni. Problem skoro nikad nije u dizajnu. Problem je u tome ï¿½to sajt ne radi ono za ï¿½ta je napravljen.",
    "date": "2026-02-27",
    "category": "CRO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-napisati-ponudu-koja-zatvara-posao",
    "title": "Kako napisati ponudu koja zatvara posao za 24 sata",
    "excerpt": "Vecina ponuda zavrï¿½i u folderu \"procitacu kasnije\" i nikad se ne otvori ponovo. Evo strukture koja tera klijenta da odgovori danas.",
    "date": "2026-02-27",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "facebook-vs-instagram-oglasi-gde-je-vasa-publika",
    "title": "Facebook vs Instagram oglasi: gde je vaï¿½a publika?",
    "excerpt": "Obe platforme koriste isti Ads Manager, ali publika se ponaï¿½a potpuno drugacije. Pogreï¿½an izbor platforme znaci bacanje budï¿½eta.",
    "date": "2026-02-27",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "koliko-kosta-los-marketing",
    "title": "Koliko zapravo koï¿½ta loï¿½ marketing (skriveni troï¿½kovi koje niko ne pominje)",
    "excerpt": "Loï¿½ marketing nije besplatan samo zato ï¿½to ne daje rezultate. Koï¿½ta vas mnogo viï¿½e nego ï¿½to mislite, i to na mestima gde ne gledate.",
    "date": "2026-02-27",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-napraviti-landing-stranicu-koja-konvertuje",
    "title": "Kako napraviti landing stranicu koja konvertuje 20%+",
    "excerpt": "Vecina landing stranica konvertuje 2-3% posetilaca. Neke konvertuju 20% i viï¿½e. Razlika nije u dizajnu. Razlika je u strukturi.",
    "date": "2026-02-27",
    "category": "CRO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-povecati-online-prodaju",
    "title": "Kako povecati prodaju online prodavnice: 10 konkretnih koraka",
    "excerpt": "Imati web shop i imati web shop koji prodaje su dve potpuno razlicite stvari. Evo ï¿½ta zapravo radi na srpskom trï¿½iï¿½tu u 2026.",
    "date": "2026-03-05",
    "category": "E-Commerce",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "jednacina-vrednosti-zasto-ljudi-kupuju",
    "title": "Jednacina vrednosti: zaï¿½to ljudi kupuju (ili ne kupuju) od vas",
    "excerpt": "Postoji formula za percepciju vrednosti. Ako je razumete, moï¿½ete prodati isti proizvod za duplo vecu cenu. Ako ne, i najniï¿½a cena ce vam biti previsoka.",
    "date": "2026-03-05",
    "category": "Prodaja",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "cetiri-nacina-da-dobijete-klijente",
    "title": "Cetiri nacina da dobijete klijente (i koji je pravi za vas)",
    "excerpt": "Svaki biznis koristi jedan od cetiri glavna kanala za dolazak do klijenata. Razlika je u tome koji kanal bira i koliko ga disciplinovano koristi.",
    "date": "2026-03-05",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-skalirati-placene-oglase-bez-bacanja-novca",
    "title": "Kako skalirati placene oglase bez bacanja novca",
    "excerpt": "Vecina firmi koje koriste placene oglase ili troï¿½i premalo da vidi rezultate ili previï¿½e na pogreï¿½ne stvari. Evo sistema za skaliranje koji zapravo funkcioniï¿½e.",
    "date": "2026-03-05",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "netokracija-cro-case",
    "title": "DRAFT: Kako smo povecali profit 4x kroz nekoliko kljucnih CRO izmena na domacem web shopu",
    "excerpt": "Prica iz prakse: najveci domaci brend anatomske obuce je kroz nekoliko pametnih promena podigao profit 4x. Evo ï¿½ta je tacno uradeno i kako to moï¿½ete da primenite.",
    "date": "2026-03-08",
    "category": "E-Commerce",
    "readTime": "11 min",
    "isDraft": true
  },
  {
    "slug": "hormozi-ponuda-kojoj-klijent-ne-kaze-ne",
    "title": "Alex Hormozi pristup: kako da napravite ponudu kojoj klijent teï¿½ko kaï¿½e ne",
    "excerpt": "Dobra usluga nije dovoljna ako ponuda nije jasna. Evo prakticnog okvira kako da formirate ponudu koja smanjuje rizik klijenta i povecava prodaju.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-sistem-za-rast-biznisa",
    "title": "Leila Hormozi lekcija: zaï¿½to biznis ne raste bez jasnog sistema",
    "excerpt": "Mnogo firmi ne zapinje na prodaji, nego na haosu posle prodaje. Evo jednostavnog okvira kako da uvedete sistem i rastete bez gaï¿½enja poï¿½ara svaki dan.",
    "date": "2026-03-10",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-kako-do-vise-upita-bez-veceg-budzeta",
    "title": "Sabri Suby pristup: kako do viï¿½e upita bez veceg budï¿½eta",
    "excerpt": "Ako oglasi troï¿½e budï¿½et, a upiti stoje, problem cesto nije cena klika nego poruka i ponuda. Evo prakticnog okvira koji moï¿½ete odmah da primenite.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-grand-slam-ponuda-za-usluge",
    "title": "Alex Hormozi Grand Slam ponuda: kako da uslugu pretvorite u ponudu koju je teï¿½ko odbiti",
    "excerpt": "Dobar marketing ne pomaï¿½e ako je ponuda slaba. Evo jednostavnog okvira kako da podignete vrednost usluge, smanjite rizik za klijenta i ubrzate odluku.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-kpi-tabla-za-stabilan-rast",
    "title": "Leila Hormozi KPI tabla: kako da vodiï¿½ firmu bez haosa i gaï¿½enja poï¿½ara",
    "excerpt": "Kad tim nema jasne brojeve, odluke se donose po osecaju. Evo jednostavne KPI table koja pomaï¿½e da vidiï¿½ ï¿½ta stvarno koci rast i ï¿½ta prvo popraviti.",
    "date": "2026-03-10",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "koliko-traje-seo-da-donese-rezultate-u-srbiji",
    "title": "Koliko traje SEO da donese rezultate u Srbiji (realni rokovi za 2026)",
    "excerpt": "SEO nije sprint ni magija preko noci. Pogledajte realne rokove po fazama, ï¿½ta se meri u prvih 30/60/90 dana i kako da znate da li strategija stvarno radi.",
    "date": "2026-03-10",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-business-profil-optimizacija-cena-srbija-2026",
    "title": "Google Business profil optimizacija: cena u Srbiji 2026 i ï¿½ta realno dobijate",
    "excerpt": "Google Business optimizacija ne kosta isto za svaku firmu. Evo realnih cena u Srbiji, sta mora da udje u posao i kako da procenis da li se ulaganje isplati.",
    "date": "2026-03-10",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "cena-odrzavanja-wordpress-sajta-srbija-2026",
    "title": "Cena odrï¿½avanja WordPress sajta u Srbiji 2026: ï¿½ta ulazi i koliko realno koï¿½ta",
    "excerpt": "Nije isto da li neko samo klikne update jednom mesecno ili stvarno cuva sajt od pada, hakovanja i gubitka leadova. Evo realnih cena odrzavanja WordPress sajta u Srbiji.",
    "date": "2026-03-10",
    "category": "WordPress",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-drustvenih-mreza-cena-srbija-2026",
    "title": "Vodenje druï¿½tvenih mreï¿½a cena u Srbiji 2026: ï¿½ta ulazi i koliko realno koï¿½ta",
    "excerpt": "Cene vodenja drustvenih mreza idu od 150e do 2.000e+ mesecno, ali razlika nije samo u broju objava. Evo sta stvarno placate i koji paket ima smisla za vas biznis.",
    "date": "2026-03-10",
    "category": "Digitalni marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-offer-stack-google-ads-leadovi-srbija-2026",
    "title": "Sabri Suby offer stack za Google Ads leadove u Srbiji 2026",
    "excerpt": "Kako da primenis Sabri Suby offer stack pristup za vise kvalifikovanih leadova iz Google oglasa: jasna ponuda, bolji landing i realan 30-dnevni plan.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-kada-zaposliti-prvog-marketing-menadzera",
    "title": "Leila Hormozi: kada je pravo vreme da zaposlite prvog marketing menadzera",
    "excerpt": "Praktican vodic kada i kako da zaposlite prvog marketing menadzera bez skupih gresaka: signali, scorecard, 30-60-90 plan i sta meriti odmah.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "tiktok-reklame-cena-srbija-2026",
    "title": "TikTok reklame cena u Srbiji 2026: realni budzeti, CPM/CPC rasponi i kada se isplate",
    "excerpt": "Koliko kostaju TikTok reklame u Srbiji 2026, koji budzet ima smisla za test i kako da procenis da li kanal donosi profit ili samo jeftine preglede bez prodaje.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "koliko-brzo-google-ads-donosi-prve-klijente-srbija-2026",
    "title": "Koliko brzo Google Ads donosi prve klijente u Srbiji 2026: realni rokovi i sta meriti",
    "excerpt": "Ako tek krecete sa Google oglasima, najvece pitanje je kada stizu prvi ozbiljni leadovi. Evo realnog 7/30/90 plana, sta usporava rezultat i kako da izbegnete bacanje budzeta.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "youtube-reklame-cena-srbija-2026",
    "title": "YouTube reklame cena u Srbiji 2026: budzet, CPV/CPC rasponi i kada se isplate",
    "excerpt": "Koliko kostaju YouTube oglasi u Srbiji 2026, koji test budzet ima smisla i kako da meris da li video kampanje donose profit ili samo preglede bez prodaje.",
    "date": "2026-03-12",
    "category": "Video Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-restorane-cena-rezervacije-srbija-2026",
    "title": "Google Ads za restorane u Srbiji 2026: cena rezervacije i budzet koji puni stolove",
    "excerpt": "Koliko realno kosta Google Ads za restorane u Srbiji 2026, koji budzet ima smisla po fazama i kako da merite cenu rezervacije, a ne samo cenu klika.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-google-ads-kampanja-fee-izbor-partnera-srbija-2026",
    "title": "Vodjenje Google Ads kampanja cena u Srbiji 2026: sta ulazi u fee i kako da izaberes partnera",
    "excerpt": "Koliko realno kosta vodjenje Google Ads kampanja u Srbiji 2026, kada je fiksni fee bolji od procenta budzeta i kako da procenis da li agencija pravi profit ili samo trosi klikove.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-arhitektonske-biroe-cena-upita-srbija-2026",
    "title": "Google Ads za arhitektonske biroe u Srbiji 2026: cena upita, budzet i kvalitet lead-a",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za arhitektonske biroe u Srbiji 2026, koji budzet ima smisla po fazama i kako da povecas broj ozbiljnih upita za projekte.",
    "date": "2026-03-13",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "kako-odrediti-budzet-za-google-reklame-srbija-2026",
    "title": "Kako odrediti budzet za Google reklame u Srbiji 2026: praktican model pre prvog evra",
    "excerpt": "Korak-po-korak model kako da izracunate realan Google Ads budzet u Srbiji 2026, od maksimalnog CPL-a do test faze i skaliranja bez rasipanja para.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "linkedin-reklame-cena-srbija-2026",
    "title": "LinkedIn reklame cena u Srbiji 2026: realni CPL rasponi, budzet i kada se isplate",
    "excerpt": "Koliko kostaju LinkedIn reklame u Srbiji 2026, koji budzet ima smisla za B2B lead gen i kako da procenis da li kanal donosi pipeline ili samo skupe klikove.",
    "date": "2026-03-14",
    "category": "LinkedIn Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-auto-placeve-cena-leada-srbija-2026",
    "title": "Google Ads za auto placeve u Srbiji 2026: cena lead-a, budzet i vise ozbiljnih kupaca",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za auto placeve u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu ozbiljnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stamparije-cena-leada-srbija-2026",
    "title": "Google Ads za stamparije u Srbiji 2026: cena lead-a, budzet i vise profitabilnih B2B upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za stamparije u Srbiji 2026, koji budzet ima smisla i kako da smanjite cenu kvalitetnog upita bez praznih poziva i neisplativih poslova.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "landing-stranica-za-google-ads-cena-srbija-2026",
    "title": "Landing stranica za Google Ads: cena u Srbiji 2026, rokovi i sta stvarno ulazi",
    "excerpt": "Koliko realno kosta landing stranica za Google Ads u Srbiji 2026, koji su tipicni rasponi po fazama i sta mora da postoji da klikovi postanu upiti i prodaja.",
    "date": "2026-03-14",
    "category": "Web Design",
    "readTime": "10 min",
    "isDraft": false
  }
]
