// Auto-generated by scripts/gen-blog-index-data.mjs
// Do not edit manually. Regenerate with: npm run seo:blog-index-data

export const blogIndexPosts = [
  {
    "slug": "sabri-suby-7-hour-followup-sistem-srbija-2026",
    "title": "Sabri Suby 7-hour follow-up sistem: kako da ne gubis leadove u Srbiji 2026",
    "excerpt": "Praktican framework za firme u Srbiji: kako da uvedes brz i strukturiran follow-up koji pretvara vise upita u stvarne klijente bez povecanja ad budzeta.",
    "date": "2026-03-12",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-kozmeticki-salon-cena-termina-srbija-2026",
    "title": "Google Ads za kozmeticki salon u Srbiji 2026: cena termina i realan budzet",
    "excerpt": "Praktican vodic za vlasnice kozmetickih salona: koliko kosta Google Ads u Srbiji 2026, koji budzet ima smisla i kako da merite cenu zakazanog termina umesto praznih klikova.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-advokate-cena-klijenta-srbija-2026",
    "title": "Instagram reklame za advokate u Srbiji 2026: cena klijenta, budzet i kako da dobijes kvalitetne upite",
    "excerpt": "Koliko realno kostaju Instagram reklame za advokatske kancelarije u Srbiji 2026, koji budzet ima smisla i kako da izbegnes upite koji ne postaju klijenti.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-autoservise-cena-leada-srbija-2026",
    "title": "Google Ads za autoservise u Srbiji 2026: cena leada, budzet i kako da telefon zvoni",
    "excerpt": "Koliko realno kosta Google Ads za auto servis u Srbiji 2026, koji budzet ima smisla za start i kako da spustite cenu upita bez praznih poziva.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-instagram-ads-kampanja-cena-srbija-2026",
    "title": "Vodjenje Instagram Ads kampanja cena u Srbiji 2026: sta realno ulazi u mesecni fee",
    "excerpt": "Koliko kosta vodjenje Instagram Ads kampanja u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li agencijski fee stvarno donosi bolji CPL i veci profit.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "woocommerce-sajt-cena-srbija-2026",
    "title": "WooCommerce sajt cena u Srbiji 2026: koliko realno kosta webshop koji prodaje",
    "excerpt": "Realni rasponi za WooCommerce izradu u Srbiji 2026: sta ulazi u cenu, koji su skriveni troskovi i kako da izbegnes webshop koji izgleda lepo, a ne prodaje.",
    "date": "2026-03-12",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-weekly-scorecard-marketing-srbija-2026",
    "title": "Leila Hormozi weekly scorecard: kako da marketing sistem radi i bez vlasnika (Srbija 2026)",
    "excerpt": "Praktican Leila Hormozi pristup za firme u Srbiji: koje marketing KPI-jeve pratiti svake nedelje, kako postaviti ownership i kada menjati kanal umesto da samo dizete budzet.",
    "date": "2026-03-12",
    "category": "Marketing Strategija",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-stomatologe-cena-termina-srbija-2026",
    "title": "Instagram reklame za stomatologe u Srbiji 2026: cena termina i budzet",
    "excerpt": "Koliki budzet treba ordinaciji za Instagram oglase u Srbiji 2026 i kako da merite cenu zakazanog termina bez praznih leadova.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-restorane-cena-rezervacije-srbija-2026",
    "title": "Instagram reklame za restorane u Srbiji 2026: cena rezervacije, budzet i kreativa koja puni stolove",
    "excerpt": "Detaljan vodic za restorane: koliki budzet ima smisla za Instagram reklame u Srbiji 2026, kako da merite cenu rezervacije i koje kreativa + landing kombinacije donose vise punih termina.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-business-profil-za-stomatologe-srbija-2026",
    "title": "Google Business profil za stomatologe u Srbiji 2026: kako do vise poziva i zakazanih termina",
    "excerpt": "Praktican vodic za stomatoloske ordinacije: kako da optimizujete Google Business profil, skupite vise recenzija i pretvorite lokalne pretrage u stvarne pacijente.",
    "date": "2026-03-12",
    "category": "Lokalni SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-b2b-cena-leada-srbija-2026",
    "title": "Google Ads za B2B u Srbiji 2026: cena leada, SQL kvalitet i budzet koji ima smisla",
    "excerpt": "Koliko realno kosta Google Ads za B2B firme u Srbiji 2026, koji CPL raspon ima smisla po ni�i i kako da merite SQL kvalitet umesto da jurite jeftine leadove bez pipeline-a.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-ecommerce-cena-prodaje-srbija-2026",
    "title": "Google Ads za e-commerce u Srbiji 2026: cena prodaje, ROAS i budzet bez bacanja para",
    "excerpt": "Koliko realno kosta Google Ads za web shop u Srbiji 2026: CPC, CPA, ROAS, test budzet i koraci kako da skalis samo ono sto je profitabilno.",
    "date": "2026-03-12",
    "category": "E-Commerce",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-advokate-cena-klijenta-srbija-2026",
    "title": "Google Ads za advokate u Srbiji 2026: cena klijenta, budzet i kako da ne bacite novac",
    "excerpt": "Realni CPC/CPL rasponi za advokatske kampanje u Srbiji 2026, koliko budzeta treba za test i kako da merite cenu klijenta umesto cene klika.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-core-4-lead-magnet-srbija-2026",
    "title": "Alex Hormozi Core 4 lead magnet sistem: kako da dobijete vise kvalitetnih upita u Srbiji 2026",
    "excerpt": "Praktican vodic kako da primenis Hormozi Core 4 lead magnet okvir na srpsko trziste i povecas broj kvalitetnih upita bez dupliranja budzeta.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stomatologe-cena-leada-srbija-2026",
    "title": "Google Ads za stomatologe u Srbiji 2026: realna cena leada i kako da ne spalite budzet",
    "excerpt": "Google Ads za stomatologe u Srbiji 2026: realni CPC i CPL rasponi, budzet za start i koraci za vise zakazanih termina.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "facebook-ads-cena-po-industriji-srbija-2026",
    "title": "Facebook Ads cena po industriji u Srbiji 2026: realni CPC/CPL rasponi i budzeti za test",
    "excerpt": "Detaljan vodic za Facebook Ads cenu po industriji u Srbiji 2026: realni rasponi CPC/CPL metrika, starter budzeti i kako da procenis kada kampanja ima zdrav ROI.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "marketing-agencija-cena-srbija-2026",
    "title": "Marketing agencija cena u Srbiji 2026: paketi, rasponi i kako da procenis isplativost",
    "excerpt": "Koliko kosta marketing agencija u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li ponuda donosi profit ili samo aktivnost bez rezultata.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "lead-generation-cena-srbija-2026",
    "title": "Lead generation cena u Srbiji 2026: koliko stvarno kosta kvalitetan upit",
    "excerpt": "Praktican vodic koliko kosta lead generation u Srbiji 2026: realni CPL rasponi, sta podize cenu i kako da razlikujete \"jeftin lead\" od profitabilnog upita.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-seo-cena-zrenjanin-2026",
    "title": "Lokalni SEO cena u Zrenjaninu 2026: koliko ko�ta i �ta realno dobijate",
    "excerpt": "Praktican vodic za lokalni SEO u Zrenjaninu: realni rasponi cena, �ta mora da ulazi u uslugu i kako da procenite da li ponuda donosi upite ili samo \"aktivnost\".",
    "date": "2026-03-11",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-instagram-profila-cena-srbija-2026",
    "title": "Vodenje Instagram profila cena u Srbiji 2026: �ta ulazi u paket i koliko je realno",
    "excerpt": "Koliko ko�ta vodenje Instagram profila u Srbiji 2026, koje su realne razlike izmedu paketa i kako da izbegnete uslugu koja izgleda jeftino, a ne donosi rezultate.",
    "date": "2026-03-11",
    "category": "Social Media",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-ads-cena-po-kliku-srbija-2026",
    "title": "Instagram Ads cena po kliku u Srbiji 2026: realni CPC rasponi i bud�et plan",
    "excerpt": "Koliko realno ko�ta klik na Instagram oglasima u Srbiji 2026, od cega zavisi CPC i kako da planirate bud�et bez skupih gre�aka.",
    "date": "2026-03-11",
    "category": "Instagram Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-100m-leads-sistem-za-vise-upita-srbija-2026",
    "title": "Alex Hormozi 100M Leads: sistem za vi�e upita bez duplog bud�eta (Srbija 2026)",
    "excerpt": "Kako da primeni� Hormozi 100M Leads pristup na srpsko tr�i�te: bolji hook, jasnija ponuda i kvalitetniji leadovi bez bacanja bud�eta.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-lokalne-biznise-kako-spustiti-cenu-leada-srbija-2026",
    "title": "Google Ads za lokalne biznise: kako spustiti cenu leada u Srbiji 2026",
    "excerpt": "Praktican vodic za lokalne firme u Srbiji: kako da kroz bolju strukturu kampanje i landing stranicu smanjite cenu upita bez povecanja bud�eta.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-value-equation-ponuda-koja-prodaje-srbija-2026",
    "title": "Alex Hormozi Value Equation: kako da ponuda bude skuplja i lak�a za prodaju (Srbija 2026)",
    "excerpt": "Praktican vodic kako da primeni� Hormozi value equation na uslu�ni biznis u Srbiji i podigne� cenu bez pada konverzije.",
    "date": "2026-03-10",
    "category": "Prodaja",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-cena-po-kliku-srbija-2026",
    "title": "Google Ads cena po kliku u Srbiji 2026: realni CPC rasponi po ni�i i intentu",
    "excerpt": "Koliko Google Ads klik realno kosta u Srbiji 2026, zasto isti upit ne placa isto svaka firma i kako da procenis da li ti je CPC zdrav ili samo deluje jeftino.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-google-ads-kampanja-cena-srbija-2026",
    "title": "Vodenje Google Ads kampanja: cena u Srbiji 2026 (�ta ulazi u uslugu)",
    "excerpt": "Koliko ko�ta vodenje Google Ads kampanja u Srbiji 2026, �ta ulazi u mesecni fee i kako da procenite da li je ponuda agencije realna ili preskupa.",
    "date": "2026-03-10",
    "category": "Google Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "izrada-landing-stranice-cena-rokovi-sta-ulazi-u-cenu",
    "title": "Izrada landing stranice: cena, rokovi, �ta ulazi u cenu (Srbija 2026)",
    "excerpt": "Koliko realno kosta landing stranica u Srbiji 2026, sta ulazi u cenu, gde firme najcesce pogrese i kako da procenis da li je ponuda zdrava ili samo izgleda jeftino.",
    "date": "2026-03-11",
    "category": "Web Design",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "copywriting-formule-koje-rade",
    "title": "Kako napisati oglas koji prodaje: copywriting formule koje rade",
    "excerpt": "Nije bitno koliko ljudi vidi va� oglas. Bitno je koliko ih ne mo�e da odoli a da ne klikne. Evo formula koje to posti�u.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ab-testiranje-male-promene-veliki-rezultati",
    "title": "A/B testiranje: male promene, veliki rezultati",
    "excerpt": "Promena boje dugmeta sama po sebi nece spasiti lo� sajt, ali prava A/B testiranja mogu udvostruciti konverzije kada se testira ponuda, struktura i CTA tok.",
    "date": "2026-02-21",
    "category": "CRO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "kako-meriti-roi-marketinga-kpi-vodic",
    "title": "Kako meriti ROI marketinga: KPI vodic za vlasnike firmi",
    "excerpt": "Ako ne merite marketing, kockate se bud�etom. Ovo je 8 kljucnih KPI brojeva koje svaka firma treba da prati da bi znala �ta donosi profit, a �ta tro�i novac.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "lead-magneti-koji-zapravo-konvertuju",
    "title": "Lead magneti koji zapravo konvertuju",
    "excerpt": "Besplatan PDF koji niko ne preuzme nije lead magnet. Pravi lead magnet pogada tacan problem publike i pretvara posetioce u kvalifikovane upite.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "brending-za-male-firme-identitet-vazniji-od-loga",
    "title": "Brending za male firme: za�to je identitet va�niji od loga",
    "excerpt": "Logo je samo pocetak. Brend je utisak koji ljudi pamte. Evo kako male firme grade jasan identitet koji podi�e poverenje, cenu i prodaju.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "video-marketing-zasto-video-dominira",
    "title": "Video marketing: za�to video dominira i kako poceti",
    "excerpt": "Video cini 82% internet saobracaja. Firme koje ne koriste video gube pa�nju publike pre prvog kontakta sa ponudom i ostaju korak iza konkurencije.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "5 min",
    "isDraft": false
  },
  {
    "slug": "seo-vs-ppc-sta-je-bolje-za-dugorocni-rast",
    "title": "SEO vs PPC: �ta je bolje za dugorocni rast",
    "excerpt": "SEO je maraton, PPC je sprint. Za vecinu firmi najbolji rast dolazi iz pametne kombinacije oba kanala, uz jasan plan bud�eta i ciljeva.",
    "date": "2026-02-21",
    "category": "SEO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "psihologija-zaradjivanja-mentalni-blokovi",
    "title": "Psihologija zaradivanja: mentalni blokovi koji koce rast firme",
    "excerpt": "Najveca prepreka rastu cesto nije tr�i�te, vec nacin razmi�ljanja vlasnika firme. Evo koji mentalni blokovi koce zaradu i kako da ih razbijete.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "komunikacija-u-prodaji-kako-napisati-ponudu",
    "title": "Komunikacija u prodaji: kako napisati ponudu koja zatvara",
    "excerpt": "Ponude koje se �alju i zaborave vs ponude nakon kojih klijent pita \"Kad mo�emo da pocnemo?\" Razlika je u strukturi.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "kako-izabrati-pravu-marketing-agenciju",
    "title": "Kako izabrati pravu marketing agenciju (i ne baciti novac)",
    "excerpt": "Tr�i�te je puno agencija koje obecavaju rezultate. Evo 7 znakova koji razlikuju agencije koje isporucuju od onih koje pricaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "social-proof-recenzije-za-vise-prodaje",
    "title": "Social proof: kako koristiti recenzije za vi�e prodaje",
    "excerpt": "92% kupaca cita recenzije pre kupovine. Evo kako da recenzije rade za vas umesto da stoje kao ukras na sajtu.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "retargeting-zasto-95-posetilaca-ne-kupi",
    "title": "Retargeting: za�to 95% posetilaca nikad ne kupi iz prvog poku�aja",
    "excerpt": "Placate saobracaj koji odlazi. Retargeting vraca te ljude po ceni i do 5-10x ni�oj od prvog klika i pretvara izgubljene posete u konkretne upite i prodaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "5 min",
    "isDraft": false
  },
  {
    "slug": "customer-retention-zadrzati-vs-naci-novog",
    "title": "Customer retention: za�to je jeftinije zadr�ati nego naci novog kupca",
    "excerpt": "Novi kupac ko�ta 5-7x vi�e od zadr�avanja postojeceg. Ovaj vodic pokazuje kako retention strategije povecavaju profit bez dizanja bud�eta za akviziciju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "17-godina-marketing-iskustva",
    "title": "17 godina marketing iskustva u jednom tekstu",
    "excerpt": "�ta se menja u marketingu, a �ta ostaje isto decenijama? Evo lekcija koje ko�taju godine i milione da se nauce.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "13-godina-poslovnog-iskustva-najskuplje-greske",
    "title": "13 godina poslovnog iskustva: najskuplje gre�ke koje firme prave",
    "excerpt": "Svaka od ovih gre�aka ko�ta firme hiljade evra i mesece izgubljenog vremena. Ovo su lekcije iz 13 godina rada koje mogu odmah da vam sacuvaju bud�et.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "od-nule-do-prvog-miliona-konkretni-koraci",
    "title": "Od nule do prvog miliona: konkretni koraci za vlasnike firmi",
    "excerpt": "Nema precica, ali postoji redosled koji �tedi godine lutanja. Ovo su koraci koji najbr�e vode od starta biznisa do prvog miliona prihoda.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-se-kretati-10x-brze-kao-vlasnik-firme",
    "title": "Kako se kretati 10x br�e kao vlasnik firme",
    "excerpt": "Produktivnost nije o tome da radite vi�e sati. Produktivnost je o eliminaciji svega �to ne proizvodi rezultate.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "zasto-vecina-firmi-stagnira-posle-prvog-miliona",
    "title": "Za�to vecina firmi stagnira posle prvog miliona",
    "excerpt": "Dostizanje prvog miliona zahteva jednu vrstu posla, ali prelazak na sledeci nivo tra�i drugaciji sistem, timsku strukturu i disciplinu izvr�enja.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "od-nule-do-prvih-10000-evra-mesecno",
    "title": "Od nule do prvih 10.000 evra mesecno: vodic za pocetnike",
    "excerpt": "Prvih 10.000� mesecno nije o talentu. O konkretnim koracima koji se mogu ponoviti u skoro svakoj industriji.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "pricing-psihologija-kontrola-percepcije-cene",
    "title": "Pricing psihologija: kako brendovi kontroli�u percepciju cene",
    "excerpt": "Cena nije broj. Cena je prica koju kupac prica sam sebi. Evo kako firme koje naplacuju 10x vi�e koriste psihologiju da to opravdaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ponuda-koju-niko-ne-moze-da-odbije",
    "title": "Anatomija neodoljive ponude: za�to vecina firmi prodaje pogre�no",
    "excerpt": "Vecina firmi se takmici cenom. Firme koje razumeju anatomiju ponude se takmice vredno�cu. Evo kako napraviti ponudu koja se ne odbija.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "organski-doseg-umire-sta-raditi",
    "title": "Za�to organski doseg umire i �ta pametne firme rade umesto toga",
    "excerpt": "Facebook organski doseg pao na 2%. Instagram sledi isti trend. Evo �ta firme koje i dalje rastu rade drugacije.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-vs-facebook-ads-koji-je-bolji",
    "title": "Google Ads vs Facebook Ads: koji je bolji za va� biznis",
    "excerpt": "Google Ads hvata ljude koji aktivno tra�e re�enje, Facebook Ads ljude koji tek otkrivaju ponudu. Pravi izbor zavisi od mar�e, cilja kampanje i brzine povrata.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "content-marketing-dugorocna-investicija",
    "title": "Content marketing: investicija koja se vraca godinama",
    "excerpt": "Blog post koji ste napisali pre 2 godine i dalje donosi saobracaj. Facebook oglas od pre 2 godine ne donosi ni�ta. Evo za�to je to bitno.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "sales-funnel-koji-radi-na-autopilotu",
    "title": "Kako napraviti sales funnel koji radi dok vi spavate",
    "excerpt": "Dok vi spavate, funnel hvata posetioce, gradi poverenje i zatvara prodaju. Ali samo ako je pravilno napravljen.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-seo-kako-se-pojaviti-prvi",
    "title": "Lokalni SEO: kako se pojaviti prvi kad neko pretra�i u va�em gradu",
    "excerpt": "Kada neko iz va�eg grada pretra�i uslugu koju nudite, va�a firma treba da bude prva. 46% svih Google pretraga ima lokalnu nameru. Evo kako napraviti da budete vi taj koji se pojavi.",
    "date": "2026-02-20",
    "category": "SEO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "email-marketing-kralj-konverzija",
    "title": "Email marketing: za�to je email i dalje kralj konverzija",
    "excerpt": "Email marketing i dalje daje vrhunski povrat ulaganja. Saznajte kako e-commerce i uslu�ne firme kroz email povecavaju ponovne kupovine i mesecni prihod.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "5-gresaka-landing-stranice-konverzije",
    "title": "5 gre�aka na landing stranicama koje ubijaju konverzije",
    "excerpt": "Vecina landing stranica izgubi 90-95% posetilaca bez konverzije. Problem obicno nisu posetilokupci vec dizajn koji sabotira odluku. Evo pet gre�aka koje ko�taju najvi�e.",
    "date": "2026-02-20",
    "category": "CRO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "facebook-oglasi-koji-zapravo-rade",
    "title": "Facebook oglasi koji zapravo rade: psihologija iza klika",
    "excerpt": "Vecina firmi tro�i novac na Facebook oglase koji izgledaju kao oglasi. A ljudi mrze oglase. Evo kako napraviti oglas koji izgleda kao sadr�aj i konvertuje kao ludo.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "piramida-kupaca-4-tipa-publike",
    "title": "Piramida kupaca: za�to vecina firmi gubi 97% tr�i�ta",
    "excerpt": "Vecina firmi se bori za isti mali procenat kupaca koji su spremni da kupe odmah. U meduvremenu, ogromna vecina tr�i�ta prolazi pored njih nezapa�eno.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "pricing-psihologija-kako-luksuzni-brendovi-kontrolisu-percepciju-cene",
    "title": "Pricing psihologija: kako luksuzni brendovi kontroli�u percepciju cene",
    "excerpt": "Cena nije broj. Cena je prica. Firme koje ovo razumeju ne prodaju jeftinije od konkurencije. Prodaju drugacije.",
    "date": "2026-02-24",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "17-godina-marketing-iskustva-u-jednom-tekstu",
    "title": "17 godina marketing iskustva u jednom tekstu",
    "excerpt": "Marketing se menja svake godine. Kanali dolaze i odlaze. Ali principi koji zapravo donose rezultate ostaju isti decenijama.",
    "date": "2026-02-24",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-napraviti-marketing-budzet-koji-ima-smisla",
    "title": "Kako napraviti marketing bud�et koji ima smisla",
    "excerpt": "Vecina firmi ili tro�i premalo na marketing pa se ni�ta ne de�ava, ili tro�i bez plana pa ne zna �ta radi. Evo kako to srediti.",
    "date": "2026-02-24",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ugc-buducnost-oglasa",
    "title": "Za�to je UGC buducnost oglasa (i kako ga koristiti)",
    "excerpt": "Profesionalni oglasi sve slabije konvertuju. Sadr�aj koji izgleda kao da ga je snimio kupac radi bolje od studijskog materijala.",
    "date": "2026-02-24",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "automatizacija-marketinga-sta-mozete-delegirati-masini",
    "title": "Automatizacija marketinga: �ta mo�ete delegirati ma�ini",
    "excerpt": "Neki zadaci tro�e sate va�eg vremena svake nedelje, a mogli bi da se zavr�e bez ijednog klika. Pitanje je samo koje.",
    "date": "2026-02-26",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-biznis-vs-online-hibridna-strategija",
    "title": "Lokalni biznis vs. online: za�to hibridna strategija pobeduje",
    "excerpt": "Cist online ili cist offline pristup ostavlja novac na stolu. Firme koje kombinuju oba kanala rastu br�e od onih koje biraju stranu.",
    "date": "2026-02-26",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-citati-marketing-izvestaj",
    "title": "Kako citati marketing izve�taj (vodic za vlasnike firmi)",
    "excerpt": "Vecina vlasnika firmi dobije mesecni izve�taj od agencije i ne zna �ta gleda. Evo �ta zapravo treba da tra�ite u brojevima.",
    "date": "2026-02-26",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "zasto-vas-sajt-ne-prodaje",
    "title": "Za�to va� sajt ne prodaje (i �ta da promenite danas)",
    "excerpt": "Sajt izgleda lepo, ali telefon ne zvoni. Problem skoro nikad nije u dizajnu. Problem je u tome �to sajt ne radi ono za �ta je napravljen.",
    "date": "2026-02-27",
    "category": "CRO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-napisati-ponudu-koja-zatvara-posao",
    "title": "Kako napisati ponudu koja zatvara posao za 24 sata",
    "excerpt": "Vecina ponuda zavr�i u folderu \"procitacu kasnije\" i nikad se ne otvori ponovo. Evo strukture koja tera klijenta da odgovori danas.",
    "date": "2026-02-27",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "facebook-vs-instagram-oglasi-gde-je-vasa-publika",
    "title": "Facebook vs Instagram oglasi: gde je va�a publika?",
    "excerpt": "Obe platforme koriste isti Ads Manager, ali publika se pona�a potpuno drugacije. Pogre�an izbor platforme znaci bacanje bud�eta.",
    "date": "2026-02-27",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "koliko-kosta-los-marketing",
    "title": "Koliko zapravo ko�ta lo� marketing (skriveni tro�kovi koje niko ne pominje)",
    "excerpt": "Lo� marketing nije besplatan samo zato �to ne daje rezultate. Ko�ta vas mnogo vi�e nego �to mislite, i to na mestima gde ne gledate.",
    "date": "2026-02-27",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-napraviti-landing-stranicu-koja-konvertuje",
    "title": "Kako napraviti landing stranicu koja konvertuje 20%+",
    "excerpt": "Vecina landing stranica konvertuje 2-3% posetilaca. Neke konvertuju 20% i vi�e. Razlika nije u dizajnu. Razlika je u strukturi.",
    "date": "2026-02-27",
    "category": "CRO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-povecati-online-prodaju",
    "title": "Kako povecati prodaju online prodavnice: 10 konkretnih koraka",
    "excerpt": "Imati web shop i imati web shop koji prodaje su dve potpuno razlicite stvari. Evo �ta zapravo radi na srpskom tr�i�tu u 2026.",
    "date": "2026-03-05",
    "category": "E-Commerce",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "jednacina-vrednosti-zasto-ljudi-kupuju",
    "title": "Jednacina vrednosti: za�to ljudi kupuju (ili ne kupuju) od vas",
    "excerpt": "Postoji formula za percepciju vrednosti. Ako je razumete, mo�ete prodati isti proizvod za duplo vecu cenu. Ako ne, i najni�a cena ce vam biti previsoka.",
    "date": "2026-03-05",
    "category": "Prodaja",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "cetiri-nacina-da-dobijete-klijente",
    "title": "Cetiri nacina da dobijete klijente (i koji je pravi za vas)",
    "excerpt": "Svaki biznis na svetu koristi jedan od cetiri kanala za pridobijanje klijenata. Razlika izmedu firmi koje rastu i onih koje stagniraju je u tome koji kanal biraju i koliko ga dobro koriste.",
    "date": "2026-03-05",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-skalirati-placene-oglase-bez-bacanja-novca",
    "title": "Kako skalirati placene oglase bez bacanja novca",
    "excerpt": "Vecina firmi koje koriste placene oglase ili tro�i premalo da vidi rezultate ili previ�e na pogre�ne stvari. Evo sistema za skaliranje koji zapravo funkcioni�e.",
    "date": "2026-03-05",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "netokracija-cro-case",
    "title": "DRAFT: Kako smo povecali profit 4x kroz nekoliko kljucnih CRO izmena na domacem web shopu",
    "excerpt": "Prica iz prakse: najveci domaci brend anatomske obuce je kroz nekoliko pametnih promena podigao profit 4x. Evo �ta je tacno uradeno i kako to mo�ete da primenite.",
    "date": "2026-03-08",
    "category": "E-Commerce",
    "readTime": "11 min",
    "isDraft": true
  },
  {
    "slug": "hormozi-ponuda-kojoj-klijent-ne-kaze-ne",
    "title": "Alex Hormozi pristup: kako da napravite ponudu kojoj klijent te�ko ka�e ne",
    "excerpt": "Dobra usluga nije dovoljna ako ponuda nije jasna. Evo prakticnog okvira kako da formirate ponudu koja smanjuje rizik klijenta i povecava prodaju.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-sistem-za-rast-biznisa",
    "title": "Leila Hormozi lekcija: za�to biznis ne raste bez jasnog sistema",
    "excerpt": "Mnogo firmi ne zapinje na prodaji, nego na haosu posle prodaje. Evo jednostavnog okvira kako da uvedete sistem i rastete bez ga�enja po�ara svaki dan.",
    "date": "2026-03-10",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-kako-do-vise-upita-bez-veceg-budzeta",
    "title": "Sabri Suby pristup: kako do vi�e upita bez veceg bud�eta",
    "excerpt": "Ako oglasi tro�e bud�et, a upiti stoje, problem cesto nije cena klika nego poruka i ponuda. Evo prakticnog okvira koji mo�ete odmah da primenite.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-grand-slam-ponuda-za-usluge",
    "title": "Alex Hormozi Grand Slam ponuda: kako da uslugu pretvorite u ponudu koju je te�ko odbiti",
    "excerpt": "Dobar marketing ne poma�e ako je ponuda slaba. Evo jednostavnog okvira kako da podignete vrednost usluge, smanjite rizik za klijenta i ubrzate odluku.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-kpi-tabla-za-stabilan-rast",
    "title": "Leila Hormozi KPI tabla: kako da vodi� firmu bez haosa i ga�enja po�ara",
    "excerpt": "Kad tim nema jasne brojeve, odluke se donose po osecaju. Evo jednostavne KPI table koja poma�e da vidi� �ta stvarno koci rast i �ta prvo popraviti.",
    "date": "2026-03-10",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "koliko-traje-seo-da-donese-rezultate-u-srbiji",
    "title": "Koliko traje SEO da donese rezultate u Srbiji (realni rokovi za 2026)",
    "excerpt": "SEO nije sprint ni magija preko noci. Pogledajte realne rokove po fazama, �ta se meri u prvih 30/60/90 dana i kako da znate da li strategija stvarno radi.",
    "date": "2026-03-10",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-business-profil-optimizacija-cena-srbija-2026",
    "title": "Google Business profil optimizacija: cena u Srbiji 2026 i �ta realno dobijate",
    "excerpt": "Ako vam tra�e od 50� do 1.000� za Google Business optimizaciju, nije ista usluga. Evo realnih raspona cena, �ta mora da ude u posao i kako da merite da li vam se ulaganje isplati.",
    "date": "2026-03-10",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "cena-odrzavanja-wordpress-sajta-srbija-2026",
    "title": "Cena odr�avanja WordPress sajta u Srbiji 2026: �ta ulazi i koliko realno ko�ta",
    "excerpt": "Nije isto da li neko samo klikne update jednom mesecno ili aktivno cuva sajt od pada, hakovanja i gubitka leadova. Evo realnih cena odr�avanja WordPress sajta u Srbiji i �ta mora da bude ukljuceno.",
    "date": "2026-03-10",
    "category": "WordPress",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-drustvenih-mreza-cena-srbija-2026",
    "title": "Vodenje dru�tvenih mre�a cena u Srbiji 2026: �ta ulazi i koliko realno ko�ta",
    "excerpt": "Cene vodenja dru�tvenih mre�a idu od 150� do 2.000�+ mesecno, ali razlika nije samo u broju objava. Evo �ta stvarno placate, koji paket ima smisla za va� biznis i kako da ne bacite bud�et.",
    "date": "2026-03-10",
    "category": "Digitalni marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-offer-stack-google-ads-leadovi-srbija-2026",
    "title": "Sabri Suby offer stack za Google Ads leadove u Srbiji 2026",
    "excerpt": "Kako da primenis Sabri Suby offer stack pristup za vise kvalifikovanih leadova iz Google oglasa: jasna ponuda, bolji landing i realan 30-dnevni plan.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-kada-zaposliti-prvog-marketing-menadzera",
    "title": "Leila Hormozi: kada je pravo vreme da zaposlite prvog marketing menadzera",
    "excerpt": "Praktican vodic kada i kako da zaposlite prvog marketing menadzera bez skupih gresaka: signali, scorecard, 30-60-90 plan i sta meriti odmah.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "tiktok-reklame-cena-srbija-2026",
    "title": "TikTok reklame cena u Srbiji 2026: realni budzeti, CPM/CPC rasponi i kada se isplate",
    "excerpt": "Koliko kostaju TikTok reklame u Srbiji 2026, koji budzet ima smisla za test i kako da procenis da li kanal donosi profit ili samo jeftine preglede bez prodaje.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "koliko-brzo-google-ads-donosi-prve-klijente-srbija-2026",
    "title": "Koliko brzo Google Ads donosi prve klijente u Srbiji 2026: realni rokovi i sta meriti",
    "excerpt": "Ako tek krecete sa Google oglasima, najvece pitanje je kada stizu prvi ozbiljni leadovi. Evo realnog 7/30/90 plana, sta usporava rezultat i kako da izbegnete bacanje budzeta.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "youtube-reklame-cena-srbija-2026",
    "title": "YouTube reklame cena u Srbiji 2026: budzet, CPV/CPC rasponi i kada se isplate",
    "excerpt": "Koliko kostaju YouTube oglasi u Srbiji 2026, koji test budzet ima smisla i kako da meris da li video kampanje donose profit ili samo preglede bez prodaje.",
    "date": "2026-03-12",
    "category": "Video Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-restorane-cena-rezervacije-srbija-2026",
    "title": "Google Ads za restorane u Srbiji 2026: cena rezervacije i budzet koji puni stolove",
    "excerpt": "Koliko realno kosta Google Ads za restorane u Srbiji 2026, koji budzet ima smisla po fazama i kako da merite cenu rezervacije, a ne samo cenu klika.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  }
]
