// Auto-generated by scripts/gen-blog-index-data.mjs
// Do not edit manually. Regenerate with: npm run seo:blog-index-data

export const blogIndexPosts = [
  {
    "slug": "marketing-strategija-za-rast-firme-srbija-2026",
    "title": "Marketing strategija za rast firme u Srbiji 2026: od prezivljavanja do skaliranja",
    "excerpt": "Zasto taktike bez strategije trose budzet. Praktican vodic za postavljanje marketing strategije koja donosi predvidljiv rast na srpskom trzistu u 2026.",
    "date": "2026-03-18",
    "category": "Marketing Strategija",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "linkedin-retargeting-b2b-kampanje-srbija-2026",
    "title": "LinkedIn retargeting: Kako vratiti B2B donosioce odluka na sajt u 2026",
    "excerpt": "Vodic za LinkedIn retargeting kampanje u Srbiji. Kako koristiti Insight Tag, Company Targeting i Document Ads za smanjenje cene lead-a i zatvaranje ugovora.",
    "date": "2026-03-18",
    "category": "LinkedIn Ads",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "linkedin-reklame-cena-b2b-marketing-srbija-2026",
    "title": "LinkedIn reklame cena u Srbiji 2026: Vodic za isplativ B2B marketing",
    "excerpt": "Koliko kostaju LinkedIn reklame u Srbiji 2026. Realan CPC, Lead Gen forme, InMail kampanje i kako smanjiti cenu klika za B2B ciljne grupe.",
    "date": "2026-03-18",
    "category": "LinkedIn Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "hladni-pozivi-cold-calling-skripta-srbija-2026",
    "title": "Hladni pozivi u Srbiji 2026: B2B skripta i strategija koja donosi sastanke",
    "excerpt": "Da li cold calling i dalje radi u Srbiji? Praktican vodic, B2B skripte za hladne pozive, prevazilazenje prigovora i kako doci do direktora.",
    "date": "2026-03-18",
    "category": "Prodaja",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "b2b-prodaja-kako-zatvoriti-klijenta-srbija-2026",
    "title": "B2B prodaja u Srbiji 2026: kako generisati leadove i zatvoriti ugovore",
    "excerpt": "Praktican vodic za B2B prodaju u Srbiji 2026. Od pronalazenja kontakata preko hladnog outreach-a do prodajnog sastanka koji konvertuje bez spustanja cene.",
    "date": "2026-03-18",
    "category": "Prodaja",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "tiktok-reklame-cena-srbija-2026",
    "title": "TikTok reklame u Srbiji 2026: cene, budzeti i ko treba da se oglasava",
    "excerpt": "Koliko kostaju TikTok reklame u Srbiji 2026. CPM i CPA benchmarci, minimalni dnevni budzeti i za koje firme ovaj kanal donosi najbolji ROI.",
    "date": "2026-03-18",
    "category": "Video Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-voditi-drustvene-mreze-srbija-2026",
    "title": "Kako samostalno voditi drustvene mreze u Srbiji 2026: alati, planiranje i organizacija vremena",
    "excerpt": "Praktican vodic za preduzetnike koji sami vode drustvene mreze. Alati za dizajn i zakazivanje postova, content kalendar i kako ustedeti vreme na drustvenim mrezama u 2026.",
    "date": "2026-03-18",
    "category": "Social Media",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "facebook-ads-remarketing-strategija-srbija-2026",
    "title": "Facebook Ads remarketing u Srbiji 2026: strategija koja vraca kupce",
    "excerpt": "Kako postaviti Facebook remarketing kampanju u Srbiji 2026. Custom Audiences, Lookalike, dinamicni oglasi i budzeti koji donose najvisi ROI.",
    "date": "2026-03-18",
    "category": "Facebook Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "email-lista-za-male-firme-srbija-2026",
    "title": "Kako izgraditi email listu od nule za male firme u Srbiji 2026",
    "excerpt": "Prakticni vodic za izgradnju email liste za male firme u Srbiji. Lead magneti koji rade, alati, landing stranice i strategija prvog meseca.",
    "date": "2026-03-18",
    "category": "Lead Generation",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "landing-page-optimizacija-konverzije-srbija-2026",
    "title": "Landing page optimizacija: 12 promena koje povecavaju konverzije za 30-80%",
    "excerpt": "Prakticne CRO promene za landing stranice u Srbiji 2026. Konkretni primeri, A/B test rezultati i greske koje kostaju konverzije.",
    "date": "2026-03-18",
    "category": "CRO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "social-media-strategija-za-male-firme-srbija-2026",
    "title": "Social media strategija za male firme u Srbiji 2026: koje mreze, koliko cesto i sta postati",
    "excerpt": "Prakticna social media strategija za male firme u Srbiji 2026. Koje platforme biriti, optimalna ucestalost objava i tipovi sadrzaja koji donose rezultate.",
    "date": "2026-03-17",
    "category": "Social Media",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "video-marketing-za-male-firme-srbija-2026",
    "title": "Video marketing za male firme u Srbiji 2026: budzet, alati i strategija bez velikog tima",
    "excerpt": "Kako male firme u Srbiji koriste video marketing 2026. Realni budzeti, alati za snimanje i montazu, platforme i tipovi videa koji donose rezultate.",
    "date": "2026-03-17",
    "category": "Video Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-pokrenuti-online-prodavnicu-srbija-2026",
    "title": "Kako pokrenuti online prodavnicu u Srbiji 2026: platforma, troskovi i prvi koraci",
    "excerpt": "Prakticni vodic za pokretanje online prodavnice u Srbiji 2026. WooCommerce vs Shopify, troskovi, placanje, dostava i marketing koji donosi prvu prodaju.",
    "date": "2026-03-17",
    "category": "E-Commerce",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "linkedin-marketing-za-b2b-firme-srbija-2026",
    "title": "LinkedIn marketing za B2B firme u Srbiji 2026: strategija, budzet i rezultati",
    "excerpt": "Kako B2B firme u Srbiji koriste LinkedIn za generisanje lead-ova 2026. Organski vs placeni, content koji radi na srpskom trzistu i realni budzeti.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-odabrati-agenciju-za-digitalni-marketing-srbija-2026",
    "title": "Kako odabrati agenciju za digitalni marketing u Srbiji 2026: 9 pitanja pre potpisivanja ugovora",
    "excerpt": "Praktican vodic kako izabrati agenciju za digitalni marketing u Srbiji 2026: koja pitanja postaviti, sta traziti u ponudi i koje crvene zastavice odmah eliminisu kandidata.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "email-marketing-cena-srbija-2026",
    "title": "Email marketing cena u Srbiji 2026: alati, strategije i realan ROI",
    "excerpt": "Koliko kosta email marketing za firmu u Srbiji 2026. Poredjenje alata (Mailchimp, Brevo, Klaviyo), cene po broju kontakata i strategije koje donose rezultate.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "web-dizajn-trendovi-srbija-2026",
    "title": "Web dizajn trendovi u Srbiji 2026: sta zapravo donosi konverzije",
    "excerpt": "Koji web dizajn trendovi zapravo pomazu srpskim firmama da prodaju vise online. Bez floskula o metaverse-u, samo ono sto radi na domacem trzistu.",
    "date": "2026-03-17",
    "category": "Web Design",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "on-page-seo-checklista-srbija-2026",
    "title": "On-page SEO checklista za sajt u Srbiji 2026: 15 koraka koji zapravo menjaju rang",
    "excerpt": "Kompletna on-page SEO checklista za srpske sajtove u 2026. Bez genericnih saveta — samo koraci koji zaista uticu na Google rang i organski saobracaj.",
    "date": "2026-03-17",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-meriti-roi-digitalnog-marketinga-srbija-2026",
    "title": "Kako meriti ROI digitalnog marketinga u Srbiji 2026: formule, alati i realni primeri",
    "excerpt": "Prakticni vodic za merenje ROI digitalnog marketinga u Srbiji. Formule, besplatni alati, KPI po kanalu i realni primeri iz srpskog trzista.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-privatne-vrtice-cena-srbija-2026",
    "title": "SEO za privatne vrtice u Srbiji 2026: cena, lokalni SEO i upisi bez oglasa",
    "excerpt": "Koliko kosta SEO optimizacija za privatni vrtic u Srbiji 2026. Realni rasponi cena, sta donosi lokalni SEO i kako popuniti grupe organskim putem.",
    "date": "2026-03-17",
    "category": "SEO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-privatne-klinike-cena-srbija-2026",
    "title": "SEO za privatne klinike u Srbiji 2026: cena, rokovi i kako privuci pacijente bez oglasa",
    "excerpt": "Koliko kosta SEO optimizacija za privatnu kliniku u Srbiji 2026. Realni rasponi cena, sta donosi lokalni SEO i zasto organski saobracaj smanjuje zavisnost od oglasa.",
    "date": "2026-03-17",
    "category": "SEO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-privatne-klinike-cena-pacijenta-srbija-2026",
    "title": "Instagram reklame za privatne klinike u Srbiji 2026: cena pacijenta i budzet plan",
    "excerpt": "Koliko realno kostaju Instagram reklame za privatne klinike u Srbiji 2026, koji budzet ima smisla po specijalizaciji i kako smanjiti cenu zakazivanja.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-racunovodje-cena-klijenta-srbija-2026",
    "title": "Google Ads za racunovodje u Srbiji 2026: cena po klijentu i budzet plan",
    "excerpt": "Koliko kosta Google Ads kampanja za knjigovodstvenu agenciju u Srbiji 2026. Realni CPC, CPL benchmarci i struktura koja donosi B2B klijente.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "b2b-marketing-srbija-2026-vodic",
    "title": "B2B marketing u Srbiji 2026: Kako do pravih klijenata bez rasipanja budzeta",
    "excerpt": "Vecina B2B firmi u Srbiji rasipa budzet na drustvene mreze koje donose samo lajkove, umesto da grade sistem koji direktno dovodi donosioce odluka. Evo sta stvarno radi u 2026.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "7 min read",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-agencije-za-nekretnine-cena-srbija-2026",
    "title": "Instagram reklame za agencije za nekretnine u Srbiji 2026: cena upita i budzet plan",
    "excerpt": "Koliko kosta Instagram oglas za agenciju za nekretnine u Srbiji 2026. CPC, CPL benchmarci i struktura kampanje koja donosi kupce i prodavce.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-agencije-za-nekretnine-cena-srbija-2026",
    "title": "SEO za agencije za nekretnine u Srbiji 2026: cena i kako rangirati listing-e",
    "excerpt": "Koliko kosta SEO za agenciju za nekretnine u Srbiji 2026. Realni rasponi cena i kako organski saobracaj moze smanjiti zavisnost od placenih portala.",
    "date": "2026-03-17",
    "category": "SEO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-teretane-cena-srbija-2026",
    "title": "SEO za teretane u Srbiji 2026: cena, rokovi i kako privuci nove clanove bez oglasa",
    "excerpt": "Koliko kosta SEO optimizacija za teretanu u Srbiji 2026. Realni rasponi cena, sta donosi lokalni SEO i zasto Google mapa moze biti jaci kanal od Instagram-a.",
    "date": "2026-03-17",
    "category": "SEO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-autoservise-cena-srbija-2026",
    "title": "SEO za autoservise u Srbiji 2026: cena, rokovi i sta donosi nove musterije",
    "excerpt": "Koliko kosta SEO optimizacija za autoservis u Srbiji 2026. Realni rasponi cena, sta ulazi u uslugu i kako Google mapa postaje vas najjaci kanal za nove klijente.",
    "date": "2026-03-17",
    "category": "SEO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-stomatologe-cena-pacijenta-srbija-2026",
    "title": "Instagram reklame za stomatologe u Srbiji 2026: cena po pacijentu i budzet plan",
    "excerpt": "Koliko kosta Instagram oglas za stomatolosku ordinaciju u Srbiji 2026. Realni CPC, CPL i budzet rasponi za zakazivanje novih pacijenata.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "izrada-sajta-za-restorane-cena-srbija-2026",
    "title": "Izrada sajta za restorane cena u Srbiji 2026: koliko kosta sajt koji stvarno donosi rezervacije",
    "excerpt": "Koliko kosta izrada sajta za restorane i kafice u Srbiji 2026, sta mora da sadrzi za dobar lokalni SEO i zasto lose postavljen meni odbija goste.",
    "date": "2026-03-16",
    "category": "Web Design",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-naci-pacijente-za-stomatolosku-ordinaciju-srbija-2026",
    "title": "Kako naci pacijente za stomatolosku ordinaciju u Srbiji (2026)",
    "excerpt": "Marketing za stomatologe se promenio. Saznajte kako da prestanete da zavisite od preporuka i izgradite stabilan sistem koji ordinaciji donosi kvalitetne pacijente svakog meseca.",
    "date": "2026-03-16",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "izrada-woocommerce-web-shopa-cena-srbija-2026",
    "title": "Izrada WooCommerce web shopa cena u Srbiji 2026: skriveni troskovi i rasponi",
    "excerpt": "Koliko realno kosta izrada WooCommerce web shopa u 2026? Pogledajte realne raspone cena, razlike izmedu sablona i custom resenja, kao i cesto zaboravljeno odrzavanje.",
    "date": "2026-03-15",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "izrada-web-shopa-cena-srbija-2026",
    "title": "Izrada web shopa cena u Srbiji 2026: koliko kosta internet prodavnica koja donosi profit",
    "excerpt": "Detaljan pregled cena za izradu web shopa u Srbiji u 2026. godini. Saznajte razlike izmedu sablona i custom resenja, kao i skrivene troskove najjeftinijih opcija.",
    "date": "2026-03-15",
    "category": "Biznis",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-drustvenih-mreza-cena-srbija-2026",
    "title": "Vodjenje drustvenih mreza cena u Srbiji 2026: Koliko realno kosta i sta dobijate",
    "excerpt": "Koliko kosta vodjenje drustvenih mreza u Srbiji 2026? Vodic kroz cene za freelancere i agencije, sta ulazi u paket i zasto najjeftinija opcija ubija prodaju.",
    "date": "2026-03-15",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "tiktok-vs-instagram-reklame-srbija-2026",
    "title": "TikTok reklame vs Instagram reklame: gde uloziti budzet u Srbiji 2026?",
    "excerpt": "Prakticno poredjenje cene klika, kvaliteta lead-ova i organskog dosega na TikToku i Instagramu za trziste Srbije. Sta se isplati za B2B, a sta za e-commerce?",
    "date": "2026-03-15",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "seo-optimizacija-za-web-shop-cena-srbija-2026",
    "title": "SEO optimizacija za web shop u Srbiji 2026: realne cene, rokovi i sta stvarno placate",
    "excerpt": "Koliko kosta SEO optimizacija za web shop u Srbiji 2026, zasto e-commerce SEO zahteva drugaciji pristup i kada se investicija stvarno isplati.",
    "date": "2026-03-15",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "landing-stranica-za-google-ads-kako-spustiti-cenu-leada-srbija-2026",
    "title": "Landing stranica za Google Ads u Srbiji 2026: kako da spustis cenu lead-a bez veceg budzeta",
    "excerpt": "Praktican vodic kako da landing stranica za Google Ads u Srbiji 2026 podigne konverziju i smanji cenu kvalifikovanog upita bez dodatnog ad spend-a.",
    "date": "2026-03-15",
    "category": "CRO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "odrzavanje-wordpress-sajta-cena-srbija-2026",
    "title": "Odrzavanje WordPress sajta cena u Srbiji 2026: mesecni paketi i sta ulazi u cenu",
    "excerpt": "Koliko realno kosta odrzavanje WordPress sajta u Srbiji 2026, koje stavke su obavezne svakog meseca i kako da izaberes paket koji cuva SEO, brzinu i sigurnost.",
    "date": "2026-03-15",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-stomatoloske-ordinacije-cena-srbija-2026",
    "title": "SEO za stomatoloske ordinacije u Srbiji 2026: cena, prioriteti i vise zakazanih pregleda",
    "excerpt": "Koliko realno kosta SEO za stomatoloske ordinacije u Srbiji 2026, sta mora da udje u paket i koje izmene najbrze podizu broj zakazanih pregleda iz organske pretrage.",
    "date": "2026-03-15",
    "category": "SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "wordpress-sajt-za-stomatolosku-ordinaciju-cena-srbija-2026",
    "title": "WordPress sajt za stomatolosku ordinaciju u Srbiji 2026: cena, rokovi i sta mora da postoji",
    "excerpt": "Koliko realno kosta WordPress sajt za stomatolosku ordinaciju u Srbiji 2026, sta ulazi u cenu i kako da sajt donosi vise zakazanih pregleda umesto samo lep dizajn.",
    "date": "2026-03-15",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-facebook-ads-kampanja-cena-srbija-2026",
    "title": "Vodjenje Facebook Ads kampanja cena u Srbiji 2026: koliko kosta i sta realno dobijas",
    "excerpt": "Koliko realno kosta vodjenje Facebook Ads kampanja u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li agencija donosi profit ili samo lep dashboard.",
    "date": "2026-03-15",
    "category": "Facebook Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-value-equation-ponuda-koja-se-prodaje-srbija-2026",
    "title": "Alex Hormozi Value Equation 2026: ponuda koja se prodaje bez spustanja cene",
    "excerpt": "Kako da primenis Alex Hormozi Value Equation na srpskom trzistu: jasna ponuda, bolji lead quality i veca vrednost klijenta bez dumping cena.",
    "date": "2026-03-15",
    "category": "Growth",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-kozmeticke-salone-cena-termina-srbija-2026",
    "title": "Instagram reklame za kozmeticke salone u Srbiji 2026: cena termina i budzet",
    "excerpt": "Koliko realno kostaju Instagram reklame za kozmeticke salone u Srbiji 2026, koji budzet ima smisla i kako da smanjite cenu zakazanog termina bez praznih poruka.",
    "date": "2026-03-15",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-krovopokrivace-cena-leada-srbija-2026",
    "title": "Google Ads za krovopokrivace u Srbiji 2026: cena lead-a, budzet i manje praznih poziva",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za krovopokrivace u Srbiji 2026, koji budzet ima smisla i kako da spustis cenu kvalifikovanog upita bez gubljenja na nerelevantne klikove.",
    "date": "2026-03-15",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-fizioterapeute-cena-termina-srbija-2026",
    "title": "Google Ads za fizioterapeute u Srbiji 2026: cena termina, budzet i kako da smanjis prazne upite",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za fizio ordinacije u Srbiji 2026, koji budzet ima smisla i kako da spustis cenu zakazanog termina bez praznih poziva.",
    "date": "2026-03-15",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "seo-audit-sajta-checklist-srbija-2026",
    "title": "SEO audit sajta u Srbiji 2026: prakticna checklista koja donosi vise upita",
    "excerpt": "Praktican SEO audit vodic za mala i srednja preduzeca u Srbiji: sta proveriti prvo, kako da prioritetizujes popravke i koje izmene najbrze donose vise kvalitetnih upita.",
    "date": "2026-03-15",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-vodoinstalatere-cena-poziva-srbija-2026",
    "title": "Google Ads za vodoinstalatere u Srbiji 2026: cena poziva, budzet i kako da ne bacas novac",
    "excerpt": "Koliko realno kosta Google Ads za vodoinstalaterske usluge u Srbiji 2026, koji je zdrav raspon cene poziva i kako da postavis kampanju koja puni raspored intervencija.",
    "date": "2026-03-15",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-privatne-skole-cena-upisa-srbija-2026",
    "title": "Google Ads za privatne skole u Srbiji 2026: cena lead-a, budzet i vise upisa",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za privatne skole u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu kvalifikovanog upita bez praznih prijava.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-privatne-vrtice-cena-upisa-srbija-2026",
    "title": "Instagram reklame za privatne vrtice u Srbiji 2026: cena upisa i budzet",
    "excerpt": "Koliko realno kostaju Instagram reklame za privatne vrtice u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalitetne prijave bez praznih poruka.",
    "date": "2026-03-14",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-veterinarske-ambulante-cena-leada-srbija-2026",
    "title": "Google Ads za veterinarske ambulante u Srbiji 2026: cena lead-a, budzet i vise pregleda",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za veterinarske ambulante u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalifikovanog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-teretane-i-fitnes-studije-cena-leada-srbija-2026",
    "title": "Google Ads za teretane i fitnes studije u Srbiji 2026: cena lead-a i budzet",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za teretane i fitnes studije u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu kvalitetne prijave.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-domove-za-stare-cena-leada-srbija-2026",
    "title": "Google Ads za domove za stare u Srbiji 2026: cena lead-a, budzet i vise ozbiljnih prijava",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za domove za stare u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalifikovanog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-agencije-za-nekretnine-cena-leada-srbija-2026",
    "title": "Google Ads za agencije za nekretnine u Srbiji 2026: cena lead-a, budzet i vise ozbiljnih kupaca",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za agencije za nekretnine u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu ozbiljnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-privatne-vrtice-cena-upisa-srbija-2026",
    "title": "Google Ads za privatne vrtice u Srbiji 2026: cena upisa, budzet i vise kvalifikovanih prijava",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za privatne vrtice u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetne prijave bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-salone-namestaja-cena-leada-srbija-2026",
    "title": "Google Ads za salone namestaja u Srbiji 2026: cena lead-a, budzet i vise kupaca",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za salone namestaja u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu kvalitetnog upita bez praznih klikova.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-skolice-stranih-jezika-cena-upisa-srbija-2026",
    "title": "Google Ads za skolice stranih jezika u Srbiji 2026: cena upisa, budzet i manje praznih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za skolice stranih jezika u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog upisa bez praznih prijava.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-autoskole-cena-upisa-srbija-2026",
    "title": "Google Ads za auto skole u Srbiji 2026: cena upisa, budzet i manje praznih poziva",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za auto skole u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog upisa bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-firme-za-selidbe-cena-poziva-srbija-2026",
    "title": "Google Ads za firme za selidbe u Srbiji 2026: cena poziva, budzet i manje izgubljenih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za firme za selidbe u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog poziva bez praznih voznji.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-privatne-klinike-cena-leada-srbija-2026",
    "title": "Google Ads za privatne klinike u Srbiji 2026: cena lead-a, budzet i manje praznih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za privatne klinike u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustis cenu kvalitetnog medicinskog upita.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "redizajn-wordpress-sajta-cena-srbija-2026",
    "title": "Redizajn WordPress sajta cena u Srbiji 2026: sta podize trosak i kako da izbegnes SEO pad",
    "excerpt": "Koliko realno kosta redizajn WordPress sajta u Srbiji 2026, sta najvise podize cenu i kako da uradis vizuelno osvezenje bez pada SEO pozicija i leadova.",
    "date": "2026-03-14",
    "category": "WordPress",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-knjigovodstvene-agencije-cena-leada-srbija-2026",
    "title": "Google Ads za knjigovodstvene agencije u Srbiji 2026: cena lead-a i profitabilan budzet",
    "excerpt": "Koliko kostaju Google Ads kampanje za knjigovodstvene agencije u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu kvalifikovanog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "facebook-reklame-za-stomatologe-cena-termina-srbija-2026",
    "title": "Facebook reklame za stomatologe u Srbiji 2026: cena termina i budzet",
    "excerpt": "Koliko realno kostaju Facebook reklame za stomatoloske ordinacije u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu zakazanog termina bez praznih leadova.",
    "date": "2026-03-14",
    "category": "Facebook Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-bravare-cena-leada-srbija-2026",
    "title": "Google Ads za bravare u Srbiji 2026: cena lead-a, budzet i vise hitnih poziva",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za bravare u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu kvalitetnog upita bez izgubljenih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-elektricare-cena-leada-srbija-2026",
    "title": "Google Ads za elektricare u Srbiji 2026: cena lead-a, budzet i vise hitnih intervencija",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za elektricare u Srbiji 2026, koji budzet ima smisla po fazama i kako da spustite cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-keramicare-cena-leada-srbija-2026",
    "title": "Google Ads za keramicare u Srbiji 2026: cena lead-a, budzet i vise kvalitetnih upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za keramicare u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjis cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-klima-servis-cena-leada-srbija-2026",
    "title": "Google Ads za klima servis u Srbiji 2026: cena lead-a, sezona i profitabilan raspored budzeta",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za klima servis u Srbiji 2026, koji budzet ima smisla po sezoni i kako da spustite cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stolare-cena-leada-srbija-2026",
    "title": "Google Ads za stolare u Srbiji 2026: cena lead-a, budzet i vise upita za namestaj po meri",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za stolare u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu kvalitetnog upita bez praznih poziva.",
    "date": "2026-03-13",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "migracija-sajta-na-wordpress-cena-srbija-2026",
    "title": "Migracija sajta na WordPress cena u Srbiji 2026: troskovi, rizici i SEO-safe plan",
    "excerpt": "Koliko realno kosta migracija sajta na WordPress u Srbiji 2026, sta najcesce podize cenu i kako da prebacis sajt bez pada pozicija, leadova i prodaje.",
    "date": "2026-03-13",
    "category": "WordPress",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "seo-optimizacija-wordpress-sajta-cena-srbija-2026",
    "title": "SEO optimizacija WordPress sajta cena u Srbiji 2026: sta ulazi i kako birati ponudu",
    "excerpt": "Koliko realno kosta SEO optimizacija WordPress sajta u Srbiji 2026, sta mora da bude ukljuceno u uslugu i kako da procenis da li ponuda donosi rast ili samo izvestaje.",
    "date": "2026-03-13",
    "category": "WordPress SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-reklame-za-vodoinstalatere-cena-leada-srbija-2026",
    "title": "Google reklame za vodoinstalatere u Srbiji 2026: cena leada, budzet i kako da telefon zvoni",
    "excerpt": "Koliko realno kostaju Google reklame za vodoinstalatere u Srbiji 2026, koji budzet ima smisla i kako da smanjite cenu upita bez gubitka kvaliteta poziva.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-reklame-za-gradjevinske-firme-cena-leada-srbija-2026",
    "title": "Google reklame za gradjevinske firme u Srbiji 2026: cena leada, budzet i profit po projektu",
    "excerpt": "Koliko realno kostaju Google reklame za gradjevinske firme u Srbiji 2026, koji budzet ima smisla i kako da spustite cenu upita bez losih leadova.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-advokate-cena-srbija-2026",
    "title": "SEO za advokate u Srbiji 2026: cena, rokovi i kako da dobijete vise kvalitetnih upita",
    "excerpt": "Koliko realno kosta SEO za advokatske kancelarije u Srbiji 2026, sta ulazi u cenu i kako da merite rezultat kroz kvalitetne pravne upite, a ne samo pozicije.",
    "date": "2026-03-12",
    "category": "Lokalni SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-autoservise-cena-upita-srbija-2026",
    "title": "Instagram reklame za autoservise u Srbiji 2026: cena upita i budzet",
    "excerpt": "Praktican vodic za autoservise: koliki Instagram budzet ima smisla, kako da merite cenu upita i koje kreativne poruke najbrze pune raspored termina.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-ads-cena-po-kliku-srbija-2026",
    "title": "Instagram Ads cena po kliku u Srbiji 2026: realni CPC rasponi i kako da spustis trosak leada",
    "excerpt": "Praktican vodič za Instagram Ads CPC u Srbiji 2026: rasponi po niši, glavni razlozi visokog klika i konkretni potezi za niži trošak uz bolji kvalitet upita.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "izrada-wordpress-sajta-cena-po-tipu-biznisa-srbija-2026",
    "title": "Izrada WordPress sajta cena po tipu biznisa u Srbiji 2026: realni rasponi i sta ulazi u cenu",
    "excerpt": "Koliko realno kosta WordPress sajt u Srbiji 2026 za usluzni biznis, ordinaciju, web shop ili B2B firmu i kako da procenis da li ponuda stvarno ima smisla.",
    "date": "2026-03-12",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "meta-ads-cena-po-kliku-srbija-2026",
    "title": "Meta Ads cena po kliku u Srbiji 2026: realni CPC rasponi i kako da spustis cenu upita",
    "excerpt": "Koliko Meta Ads klik realno kosta u Srbiji 2026 po industriji, gde kampanje najcesce gube budzet i kako da smanjis CPC bez pada kvaliteta leadova.",
    "date": "2026-03-12",
    "category": "Meta Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-onboarding-sistem-zadrzavanje-klijenata-srbija-2026",
    "title": "Leila Hormozi onboarding sistem: kako da zadrzis klijente u marketing agenciji (Srbija 2026)",
    "excerpt": "Praktican onboarding framework za agencije u Srbiji: kako da u prvih 30 dana klijent vidi progres, smanjis churn i podignes LTV bez dizanja ad budzeta.",
    "date": "2026-03-12",
    "category": "Agency Growth",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-7-hour-followup-sistem-srbija-2026",
    "title": "Sabri Suby 7-hour follow-up sistem: kako da ne gubis leadove u Srbiji 2026",
    "excerpt": "Praktican framework za firme u Srbiji: kako da uvedes brz i strukturiran follow-up koji pretvara vise upita u stvarne klijente bez povecanja ad budzeta.",
    "date": "2026-03-12",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-kozmeticki-salon-cena-termina-srbija-2026",
    "title": "Google Ads za kozmeticki salon u Srbiji 2026: cena termina i realan budzet",
    "excerpt": "Praktican vodic za vlasnice kozmetickih salona: koliko kosta Google Ads u Srbiji 2026, koji budzet ima smisla i kako da merite cenu zakazanog termina umesto praznih klikova.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-advokate-cena-klijenta-srbija-2026",
    "title": "Instagram reklame za advokate u Srbiji 2026: cena klijenta i budzet",
    "excerpt": "Koliko realno kostaju Instagram reklame za advokatske kancelarije u Srbiji 2026, koji budzet ima smisla i kako da izbegnes upite koji ne postaju klijenti.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-autoservise-cena-leada-srbija-2026",
    "title": "Google Ads za autoservise u Srbiji 2026: cena leada, budzet i kako da telefon zvoni",
    "excerpt": "Koliko realno kosta Google Ads za auto servis u Srbiji 2026, koji budzet ima smisla za start i kako da spustite cenu upita bez praznih poziva.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-instagram-ads-kampanja-cena-srbija-2026",
    "title": "Vodjenje Instagram Ads kampanja cena u Srbiji 2026: sta realno ulazi u mesecni fee",
    "excerpt": "Koliko kosta vodjenje Instagram Ads kampanja u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li agencijski fee stvarno donosi bolji CPL i veci profit.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "woocommerce-sajt-cena-srbija-2026",
    "title": "WooCommerce sajt cena u Srbiji 2026: koliko realno kosta webshop koji prodaje",
    "excerpt": "Realni rasponi za WooCommerce izradu u Srbiji 2026: sta ulazi u cenu, koji su skriveni troskovi i kako da izbegnes webshop koji izgleda lepo, a ne prodaje.",
    "date": "2026-03-12",
    "category": "WordPress",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-weekly-scorecard-marketing-srbija-2026",
    "title": "Leila Hormozi weekly scorecard: kako da marketing sistem radi i bez vlasnika (Srbija 2026)",
    "excerpt": "Praktican Leila Hormozi pristup za firme u Srbiji: koje marketing KPI-jeve pratiti svake nedelje, kako postaviti ownership i kada menjati kanal umesto da samo dizete budzet.",
    "date": "2026-03-12",
    "category": "Marketing Strategija",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-stomatologe-cena-termina-srbija-2026",
    "title": "Instagram reklame za stomatologe u Srbiji 2026: cena termina i budzet",
    "excerpt": "Koliki budzet treba ordinaciji za Instagram oglase u Srbiji 2026 i kako da merite cenu zakazanog termina bez praznih leadova.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-restorane-cena-rezervacije-srbija-2026",
    "title": "Instagram reklame za restorane u Srbiji 2026: cena rezervacije i budzet",
    "excerpt": "Koliki budzet ima smisla za Instagram reklame restorana u Srbiji 2026, kako da merite cenu rezervacije i koje poruke najcesce dovode ljude do rezervacije.",
    "date": "2026-03-12",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-business-profil-za-stomatologe-srbija-2026",
    "title": "Google Business profil za stomatologe u Srbiji 2026: kako do vise poziva i zakazanih termina",
    "excerpt": "Praktican vodic za stomatoloske ordinacije: kako da optimizujete Google Business profil, skupite vise recenzija i pretvorite lokalne pretrage u stvarne pacijente.",
    "date": "2026-03-12",
    "category": "Lokalni SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-b2b-cena-leada-srbija-2026",
    "title": "Google Ads za B2B u Srbiji 2026: cena leada, SQL kvalitet i budzet koji ima smisla",
    "excerpt": "Koliko realno kosta Google Ads za B2B firme u Srbiji 2026, koji CPL raspon ima smisla po niši i kako da merite SQL kvalitet umesto da jurite jeftine leadove bez pipeline-a.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-ecommerce-cena-prodaje-srbija-2026",
    "title": "Google Ads za e-commerce u Srbiji 2026: cena prodaje, ROAS i budzet bez bacanja para",
    "excerpt": "Koliko realno kosta Google Ads za web shop u Srbiji 2026: CPC, CPA, ROAS, test budzet i koraci kako da skalis samo ono sto je profitabilno.",
    "date": "2026-03-12",
    "category": "E-Commerce",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-advokate-cena-klijenta-srbija-2026",
    "title": "Google Ads za advokate u Srbiji 2026: cena klijenta, budzet i kako da ne bacite novac",
    "excerpt": "Realni CPC/CPL rasponi za advokatske kampanje u Srbiji 2026, koliko budzeta treba za test i kako da merite cenu klijenta umesto cene klika.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-core-4-lead-magnet-srbija-2026",
    "title": "Alex Hormozi Core 4 lead magnet sistem: kako da dobijete vise kvalitetnih upita u Srbiji 2026",
    "excerpt": "Praktican vodic kako da primenis Hormozi Core 4 lead magnet okvir na srpsko trziste i povecas broj kvalitetnih upita bez dupliranja budzeta.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stomatologe-cena-leada-srbija-2026",
    "title": "Google Ads za stomatologe u Srbiji 2026: realna cena leada i kako da ne spalite budzet",
    "excerpt": "Google Ads za stomatologe u Srbiji 2026: realni CPC i CPL rasponi, budzet za start i koraci za vise zakazanih termina.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "facebook-ads-cena-po-industriji-srbija-2026",
    "title": "Facebook Ads cena po industriji u Srbiji 2026: realni CPC/CPL rasponi i budzeti za test",
    "excerpt": "Detaljan vodic za Facebook Ads cenu po industriji u Srbiji 2026: realni rasponi CPC/CPL metrika, starter budzeti i kako da procenis kada kampanja ima zdrav ROI.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "marketing-agencija-cena-srbija-2026",
    "title": "Marketing agencija cena u Srbiji 2026: paketi, rasponi i kako da procenis isplativost",
    "excerpt": "Koliko kosta marketing agencija u Srbiji 2026, koji modeli naplate postoje i kako da procenis da li ponuda donosi profit ili samo aktivnost bez rezultata.",
    "date": "2026-03-11",
    "category": "Marketing",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "lead-generation-cena-srbija-2026",
    "title": "Lead generation cena u Srbiji 2026: koliko stvarno kosta kvalitetan upit",
    "excerpt": "Praktican vodic koliko kosta lead generation u Srbiji 2026: realni CPL rasponi, sta podize cenu i kako da razlikujete \"jeftin lead\" od profitabilnog upita.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-seo-cena-zrenjanin-2026",
    "title": "Lokalni SEO cena u Zrenjaninu 2026: koliko košta i šta realno dobijate",
    "excerpt": "Praktican vodic za lokalni SEO u Zrenjaninu: realni rasponi cena, šta mora da ulazi u uslugu i kako da procenite da li ponuda donosi upite ili samo \"aktivnost\".",
    "date": "2026-03-11",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-instagram-profila-cena-srbija-2026",
    "title": "Vodenje Instagram profila cena u Srbiji 2026: šta ulazi u paket i koliko je realno",
    "excerpt": "Koliko košta vodenje Instagram profila u Srbiji 2026, koje su realne razlike izmedu paketa i kako da izbegnete uslugu koja izgleda jeftino, a ne donosi rezultate.",
    "date": "2026-03-11",
    "category": "Social Media",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "instagram-ads-cpc-budzet-plan-srbija-2026",
    "title": "Instagram Ads cena po kliku u Srbiji 2026: realni CPC rasponi i budžet plan",
    "excerpt": "Koliko realno košta klik na Instagram oglasima u Srbiji 2026, od cega zavisi CPC i kako da planirate budžet bez skupih grešaka.",
    "date": "2026-03-11",
    "category": "Instagram Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-100m-leads-sistem-za-vise-upita-srbija-2026",
    "title": "Alex Hormozi 100M Leads: sistem za više upita bez duplog budžeta (Srbija 2026)",
    "excerpt": "Kako da primeniš Hormozi 100M Leads pristup na srpsko tržište: bolji hook, jasnija ponuda i kvalitetniji leadovi bez bacanja budžeta.",
    "date": "2026-03-11",
    "category": "Lead Generation",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-lokalne-biznise-kako-spustiti-cenu-leada-srbija-2026",
    "title": "Google Ads za lokalne biznise: kako spustiti cenu leada u Srbiji 2026",
    "excerpt": "Praktican vodic za lokalne firme u Srbiji: kako da kroz bolju strukturu kampanje i landing stranicu smanjite cenu upita bez povecanja budžeta.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-cena-po-kliku-srbija-2026",
    "title": "Google Ads cena po kliku u Srbiji 2026: realni CPC rasponi po nisi i intentu",
    "excerpt": "Koliko Google Ads klik realno kosta u Srbiji 2026, koji su rasponi po industrijama i kako da razlikujes zdrav CPC od skupe kampanje koja samo izgleda jeftino.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "12 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-google-ads-kampanja-cena-srbija-2026",
    "title": "Vodenje Google Ads kampanja: cena u Srbiji 2026 (šta ulazi u uslugu)",
    "excerpt": "Koliko košta vodenje Google Ads kampanja u Srbiji 2026, šta ulazi u mesecni fee i kako da procenite da li je ponuda agencije realna ili preskupa.",
    "date": "2026-03-10",
    "category": "Google Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "izrada-landing-stranice-cena-rokovi-sta-ulazi-u-cenu",
    "title": "Izrada landing stranice: cena, rokovi i sta ulazi u cenu (Srbija 2026)",
    "excerpt": "Koliko realno kosta izrada landing stranice u Srbiji 2026, sta tacno ulazi u cenu i kako da procenis ponudu pre nego sto potrosis budzet na saobracaj.",
    "date": "2026-03-11",
    "category": "Web Design",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "copywriting-formule-koje-rade",
    "title": "Kako napisati oglas koji prodaje: copywriting formule koje rade",
    "excerpt": "Nije bitno koliko ljudi vidi vaš oglas. Bitno je koliko ih ne može da odoli a da ne klikne. Evo formula koje to postižu.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ab-testiranje-male-promene-veliki-rezultati",
    "title": "A/B testiranje: male promene, veliki rezultati",
    "excerpt": "Promena boje dugmeta sama po sebi nece spasiti loš sajt, ali prava A/B testiranja mogu udvostruciti konverzije kada se testira ponuda, struktura i CTA tok.",
    "date": "2026-02-21",
    "category": "CRO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "kako-meriti-roi-marketinga-kpi-vodic",
    "title": "Kako meriti ROI marketinga: KPI vodic za vlasnike firmi",
    "excerpt": "Ako ne merite marketing, kockate se budžetom. Ovo je 8 kljucnih KPI brojeva koje svaka firma treba da prati da bi znala šta donosi profit, a šta troši novac.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "lead-magneti-koji-zapravo-konvertuju",
    "title": "Lead magneti koji zapravo konvertuju",
    "excerpt": "Besplatan PDF koji niko ne preuzme nije lead magnet. Pravi lead magnet pogada tacan problem publike i pretvara posetioce u kvalifikovane upite.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "brending-za-male-firme-identitet-vazniji-od-loga",
    "title": "Brending za male firme: zašto je identitet vašniji od loga",
    "excerpt": "Logo je samo pocetak. Brend je utisak koji ljudi pamte. Evo kako male firme grade jasan identitet koji podiže poverenje, cenu i prodaju.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "video-marketing-zasto-video-dominira",
    "title": "Video marketing: zašto video dominira i kako poceti",
    "excerpt": "Video cini 82% internet saobracaja. Firme koje ne koriste video gube pažnju publike pre prvog kontakta sa ponudom i ostaju korak iza konkurencije.",
    "date": "2026-02-21",
    "category": "Marketing",
    "readTime": "5 min",
    "isDraft": false
  },
  {
    "slug": "seo-vs-ppc-sta-je-bolje-za-dugorocni-rast",
    "title": "SEO vs PPC: šta je bolje za dugorocni rast",
    "excerpt": "SEO je maraton, PPC je sprint. Za vecinu firmi najbolji rast dolazi iz pametne kombinacije oba kanala, uz jasan plan budžeta i ciljeva.",
    "date": "2026-02-21",
    "category": "SEO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "psihologija-zaradjivanja-mentalni-blokovi",
    "title": "Psihologija zaradivanja: mentalni blokovi koji koce rast firme",
    "excerpt": "Najveca prepreka rastu cesto nije tržište, vec nacin razmišljanja vlasnika firme. Evo koji mentalni blokovi koce zaradu i kako da ih razbijete.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "komunikacija-u-prodaji-kako-napisati-ponudu",
    "title": "Komunikacija u prodaji: kako napisati ponudu koja zatvara",
    "excerpt": "Ponude koje se šalju i zaborave vs ponude nakon kojih klijent pita \"Kad možemo da pocnemo?\" Razlika je u strukturi.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "kako-izabrati-pravu-marketing-agenciju",
    "title": "Kako izabrati pravu marketing agenciju (i ne baciti novac)",
    "excerpt": "Tržište je puno agencija koje obecavaju rezultate. Evo 7 znakova koji razlikuju agencije koje isporucuju od onih koje pricaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "social-proof-recenzije-za-vise-prodaje",
    "title": "Social proof: kako koristiti recenzije za više prodaje",
    "excerpt": "92% kupaca cita recenzije pre kupovine. Evo kako da recenzije rade za vas umesto da stoje kao ukras na sajtu i da ih ljudi jedva primete.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "retargeting-zasto-95-posetilaca-ne-kupi",
    "title": "Retargeting: zašto 95% posetilaca nikad ne kupi iz prvog pokušaja",
    "excerpt": "Placate saobracaj koji odlazi. Retargeting vraca te ljude po ceni i do 5-10x nižoj od prvog klika i pretvara izgubljene posete u konkretne upite i prodaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "5 min",
    "isDraft": false
  },
  {
    "slug": "customer-retention-zadrzati-vs-naci-novog",
    "title": "Customer retention: zašto je jeftinije zadržati nego naci novog kupca",
    "excerpt": "Novi kupac košta 5-7x više od zadržavanja postojeceg. Ovaj vodic pokazuje kako retention strategije povecavaju profit bez dizanja budžeta za akviziciju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "17-godina-marketing-iskustva",
    "title": "17 godina marketing iskustva u jednom tekstu",
    "excerpt": "šta se menja u marketingu, a šta ostaje isto decenijama? Evo lekcija koje koštaju godine i milione da se nauce.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "13-godina-poslovnog-iskustva-najskuplje-greske",
    "title": "13 godina poslovnog iskustva: najskuplje greške koje firme prave",
    "excerpt": "Svaka od ovih grešaka košta firme hiljade evra i mesece izgubljenog vremena. Ovo su lekcije iz 13 godina rada koje mogu odmah da vam sacuvaju budžet.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "od-nule-do-prvog-miliona-konkretni-koraci",
    "title": "Od nule do prvog miliona: konkretni koraci za vlasnike firmi",
    "excerpt": "Nema precica, ali postoji redosled koji štedi godine lutanja. Ovo su koraci koji najbrže vode od starta biznisa do prvog miliona prihoda.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-se-kretati-10x-brze-kao-vlasnik-firme",
    "title": "Kako se kretati 10x brže kao vlasnik firme",
    "excerpt": "Produktivnost nije o tome da radite više sati. Produktivnost je o eliminaciji svega što ne proizvodi rezultate.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "zasto-vecina-firmi-stagnira-posle-prvog-miliona",
    "title": "Zašto vecina firmi stagnira posle prvog miliona",
    "excerpt": "Dostizanje prvog miliona zahteva jednu vrstu posla, ali prelazak na sledeci nivo traži drugaciji sistem, timsku strukturu i disciplinu izvršenja.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "od-nule-do-prvih-10000-evra-mesecno",
    "title": "Od nule do prvih 10.000 evra mesecno: vodic za pocetnike",
    "excerpt": "Prvih 10.000e mesecno retko dolazi iz talenta. Mnogo cesce dolazi iz nekoliko konkretnih koraka koji mogu da se ponove u skoro svakoj industriji.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "pricing-psihologija-kontrola-percepcije-cene",
    "title": "Pricing psihologija: kako brendovi kontrolišu percepciju cene",
    "excerpt": "Cena nije broj. Cena je prica koju kupac prica sam sebi. Evo kako firme koje naplacuju 10x više koriste psihologiju da to opravdaju.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ponuda-koju-niko-ne-moze-da-odbije",
    "title": "Anatomija neodoljive ponude: zašto vecina firmi prodaje pogrešno",
    "excerpt": "Vecina firmi se takmici cenom. Firme koje razumeju anatomiju ponude se takmice vrednošću. Evo kako napraviti ponudu koja se ne odbija.",
    "date": "2026-02-20",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "organski-doseg-umire-sta-raditi",
    "title": "Zašto organski doseg umire i šta pametne firme rade umesto toga",
    "excerpt": "Facebook organski doseg pao na 2%. Instagram sledi isti trend. Evo šta firme koje i dalje rastu rade drugacije.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-vs-facebook-ads-koji-je-bolji",
    "title": "Google Ads vs Facebook Ads: koji je bolji za vaš biznis",
    "excerpt": "Google Ads hvata ljude koji aktivno traže rešenje, Facebook Ads ljude koji tek otkrivaju ponudu. Pravi izbor zavisi od marže, cilja kampanje i brzine povrata.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "content-marketing-dugorocna-investicija",
    "title": "Content marketing: investicija koja se vraca godinama",
    "excerpt": "Blog post koji ste napisali pre 2 godine i dalje donosi saobracaj. Facebook oglas od pre 2 godine ne donosi ništa. Evo zašto je to bitno.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "sales-funnel-koji-radi-na-autopilotu",
    "title": "Kako napraviti sales funnel koji radi dok vi spavate",
    "excerpt": "Dok vi spavate, funnel hvata posetioce, gradi poverenje i zatvara prodaju. Ali samo ako je pravilno napravljen.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-seo-kako-se-pojaviti-prvi",
    "title": "Lokalni SEO: kako se pojaviti prvi kad neko pretraži u vašem gradu",
    "excerpt": "Kada neko iz vaseg grada pretrazi uslugu koju nudite, treba da vidi vas pre konkurencije. Evo kako da lokalni SEO to stvarno uradi za vas biznis.",
    "date": "2026-02-20",
    "category": "SEO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "email-marketing-kralj-konverzija",
    "title": "Email marketing: zašto je email i dalje kralj konverzija",
    "excerpt": "Email marketing i dalje daje vrhunski povrat ulaganja. Saznajte kako e-commerce i uslužne firme kroz email povecavaju ponovne kupovine i mesecni prihod.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "5-gresaka-landing-stranice-konverzije",
    "title": "5 grešaka na landing stranicama koje ubijaju konverzije",
    "excerpt": "Vecina landing stranica izgubi 90-95% posetilaca bez konverzije. Problem obicno nisu posetilokupci vec dizajn koji sabotira odluku. Evo pet grešaka koje koštaju najviše.",
    "date": "2026-02-20",
    "category": "CRO",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "facebook-oglasi-koji-zapravo-rade",
    "title": "Facebook oglasi koji zapravo rade: psihologija iza klika",
    "excerpt": "Vecina firmi troši novac na Facebook oglase koji izgledaju kao oglasi. A ljudi mrze oglase. Evo kako napraviti oglas koji izgleda kao sadržaj i konvertuje kao ludo.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "piramida-kupaca-4-tipa-publike",
    "title": "Piramida kupaca: zašto vecina firmi gubi 97% tr�išta",
    "excerpt": "Vecina firmi se bori za isti mali procenat kupaca koji su spremni da kupe odmah. U meduvremenu, ogromna vecina tr�išta prolazi pored njih nezapaženo.",
    "date": "2026-02-20",
    "category": "Marketing",
    "readTime": "6 min",
    "isDraft": false
  },
  {
    "slug": "pricing-psihologija-kako-luksuzni-brendovi-kontrolisu-percepciju-cene",
    "title": "Pricing psihologija: kako luksuzni brendovi kontrolišu percepciju cene",
    "excerpt": "Cena nije broj. Cena je prica. Firme koje ovo razumeju ne prodaju jeftinije od konkurencije. Prodaju drugacije.",
    "date": "2026-02-24",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "17-godina-marketing-iskustva-u-jednom-tekstu",
    "title": "17 godina marketing iskustva: lekcije iz jednog teksta",
    "excerpt": "Marketing se menja svake godine. Kanali dolaze i odlaze. Ali principi koji zapravo donose rezultate ostaju isti decenijama.",
    "date": "2026-02-24",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-napraviti-marketing-budzet-koji-ima-smisla",
    "title": "Kako napraviti marketing budžet koji ima smisla",
    "excerpt": "Vecina firmi ili troši premalo na marketing pa se ništa ne dešava, ili troši bez plana pa ne zna šta radi. Evo kako to srediti.",
    "date": "2026-02-24",
    "category": "Biznis",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "ugc-buducnost-oglasa",
    "title": "Zašto je UGC buducnost oglasa (i kako ga koristiti)",
    "excerpt": "Profesionalni oglasi sve slabije konvertuju. Sadržaj koji izgleda kao da ga je snimio kupac radi bolje od studijskog materijala.",
    "date": "2026-02-24",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "automatizacija-marketinga-sta-mozete-delegirati-masini",
    "title": "Automatizacija marketinga: šta možete delegirati mašini",
    "excerpt": "Neki zadaci troše sate vašeg vremena svake nedelje, a mogli bi da se završe bez ijednog klika. Pitanje je samo koje.",
    "date": "2026-02-26",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "lokalni-biznis-vs-online-hibridna-strategija",
    "title": "Lokalni biznis vs. online: zašto hibridna strategija pobeduje",
    "excerpt": "Cist online ili cist offline pristup ostavlja novac na stolu. Firme koje kombinuju oba kanala rastu brže od onih koje biraju stranu.",
    "date": "2026-02-26",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-citati-marketing-izvestaj",
    "title": "Kako citati marketing izveštaj (vodic za vlasnike firmi)",
    "excerpt": "Vecina vlasnika firmi dobije mesecni izveštaj od agencije i ne zna šta gleda. Evo šta zapravo treba da tražite u brojevima.",
    "date": "2026-02-26",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "zasto-vas-sajt-ne-prodaje",
    "title": "Zašto vaš sajt ne prodaje (i šta da promenite danas)",
    "excerpt": "Sajt izgleda lepo, ali telefon ne zvoni. Problem skoro nikad nije u dizajnu. Problem je u tome što sajt ne radi ono za šta je napravljen.",
    "date": "2026-02-27",
    "category": "CRO",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-napisati-ponudu-koja-zatvara-posao",
    "title": "Kako napisati ponudu koja zatvara posao za 24 sata",
    "excerpt": "Vecina ponuda završi u folderu \"procitacu kasnije\" i nikad se ne otvori ponovo. Evo strukture koja tera klijenta da odgovori danas.",
    "date": "2026-02-27",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "facebook-vs-instagram-oglasi-gde-je-vasa-publika",
    "title": "Facebook vs Instagram oglasi: gde je vaša publika?",
    "excerpt": "Obe platforme koriste isti Ads Manager, ali publika se ponaša potpuno drugacije. Pogrešan izbor platforme znaci bacanje budžeta.",
    "date": "2026-02-27",
    "category": "Marketing",
    "readTime": "7 min",
    "isDraft": false
  },
  {
    "slug": "koliko-kosta-los-marketing",
    "title": "Koliko zapravo košta loš marketing (skriveni troškovi koje niko ne pominje)",
    "excerpt": "Loš marketing nije besplatan samo zato što ne daje rezultate. Košta vas mnogo više nego što mislite, i to na mestima gde ne gledate.",
    "date": "2026-02-27",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "kako-napraviti-landing-stranicu-koja-konvertuje",
    "title": "Kako napraviti landing stranicu koja konvertuje 20%+",
    "excerpt": "Vecina landing stranica konvertuje 2-3% posetilaca. Neke konvertuju 20% i više. Razlika nije u dizajnu. Razlika je u strukturi.",
    "date": "2026-02-27",
    "category": "CRO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-povecati-online-prodaju",
    "title": "Kako povecati prodaju online prodavnice: 10 konkretnih koraka",
    "excerpt": "Imati web shop i imati web shop koji prodaje su dve potpuno razlicite stvari. Evo šta zapravo radi na srpskom tržištu u 2026.",
    "date": "2026-03-05",
    "category": "E-Commerce",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "jednacina-vrednosti-zasto-ljudi-kupuju",
    "title": "Jednacina vrednosti: zašto ljudi kupuju (ili ne kupuju) od vas",
    "excerpt": "Postoji formula za percepciju vrednosti. Ako je razumete, možete prodati isti proizvod za duplo vecu cenu. Ako ne, i najniža cena ce vam biti previsoka.",
    "date": "2026-03-05",
    "category": "Prodaja",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "cetiri-nacina-da-dobijete-klijente",
    "title": "Cetiri nacina da dobijete klijente (i koji je pravi za vas)",
    "excerpt": "Svaki biznis koristi jedan od cetiri glavna kanala za dolazak do klijenata. Razlika je u tome koji kanal bira i koliko ga disciplinovano koristi.",
    "date": "2026-03-05",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "kako-skalirati-placene-oglase-bez-bacanja-novca",
    "title": "Kako skalirati placene oglase bez bacanja novca",
    "excerpt": "Vecina firmi koje koriste placene oglase ili troši premalo da vidi rezultate ili previše na pogrešne stvari. Evo sistema za skaliranje koji zapravo funkcioniše.",
    "date": "2026-03-05",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "netokracija-cro-case",
    "title": "DRAFT: Kako smo povecali profit 4x kroz nekoliko kljucnih CRO izmena na domacem web shopu",
    "excerpt": "Prica iz prakse: najveci domaci brend anatomske obuce je kroz nekoliko pametnih promena podigao profit 4x. Evo šta je tacno uradeno i kako to možete da primenite.",
    "date": "2026-03-08",
    "category": "E-Commerce",
    "readTime": "11 min",
    "isDraft": true
  },
  {
    "slug": "hormozi-ponuda-kojoj-klijent-ne-kaze-ne",
    "title": "Alex Hormozi pristup: kako da napravite ponudu kojoj klijent teško kaže ne",
    "excerpt": "Dobra usluga nije dovoljna ako ponuda nije jasna. Evo prakticnog okvira kako da formirate ponudu koja smanjuje rizik klijenta i povecava prodaju.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-sistem-za-rast-biznisa",
    "title": "Leila Hormozi lekcija: zašto biznis ne raste bez jasnog sistema",
    "excerpt": "Mnogo firmi ne zapinje na prodaji, nego na haosu posle prodaje. Evo jednostavnog okvira kako da uvedete sistem i rastete bez gašenja požara svaki dan.",
    "date": "2026-03-10",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-kako-do-vise-upita-bez-veceg-budzeta",
    "title": "Sabri Suby pristup: kako do više upita bez veceg budžeta",
    "excerpt": "Ako oglasi troše budžet, a upiti stoje, problem cesto nije cena klika nego poruka i ponuda. Evo prakticnog okvira koji možete odmah da primenite.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "alex-hormozi-grand-slam-ponuda-za-usluge",
    "title": "Alex Hormozi Grand Slam ponuda: kako da uslugu pretvorite u ponudu koju je teško odbiti",
    "excerpt": "Dobar marketing ne pomaže ako je ponuda slaba. Evo jednostavnog okvira kako da podignete vrednost usluge, smanjite rizik za klijenta i ubrzate odluku.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-kpi-tabla-za-stabilan-rast",
    "title": "Leila Hormozi KPI tabla: kako da vodiš firmu bez haosa i gašenja požara",
    "excerpt": "Kad tim nema jasne brojeve, odluke se donose po osecaju. Evo jednostavne KPI table koja pomaže da vidiš šta stvarno koci rast i šta prvo popraviti.",
    "date": "2026-03-10",
    "category": "Biznis",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "koliko-traje-seo-da-donese-rezultate-u-srbiji",
    "title": "Koliko traje SEO da donese rezultate u Srbiji (realni rokovi za 2026)",
    "excerpt": "SEO nije sprint ni magija preko noci. Pogledajte realne rokove po fazama, šta se meri u prvih 30/60/90 dana i kako da znate da li strategija stvarno radi.",
    "date": "2026-03-10",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-business-profil-optimizacija-cena-srbija-2026",
    "title": "Google Business profil optimizacija: cena u Srbiji 2026 i šta realno dobijate",
    "excerpt": "Google Business optimizacija ne kosta isto za svaku firmu. Evo realnih cena u Srbiji, sta mora da udje u posao i kako da procenis da li se ulaganje isplati.",
    "date": "2026-03-10",
    "category": "SEO",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "cena-odrzavanja-wordpress-sajta-srbija-2026",
    "title": "Cena održavanja WordPress sajta u Srbiji 2026: šta ulazi i koliko realno košta",
    "excerpt": "Nije isto da li neko samo klikne update jednom mesecno ili stvarno cuva sajt od pada, hakovanja i gubitka leadova. Evo realnih cena odrzavanja WordPress sajta u Srbiji.",
    "date": "2026-03-10",
    "category": "WordPress",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "sabri-suby-offer-stack-google-ads-leadovi-srbija-2026",
    "title": "Sabri Suby offer stack za Google Ads leadove u Srbiji 2026",
    "excerpt": "Kako da primenis Sabri Suby offer stack pristup za vise kvalifikovanih leadova iz Google oglasa: jasna ponuda, bolji landing i realan 30-dnevni plan.",
    "date": "2026-03-11",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "leila-hormozi-kada-zaposliti-prvog-marketing-menadzera",
    "title": "Leila Hormozi: kada je pravo vreme da zaposlite prvog marketing menadzera",
    "excerpt": "Praktican vodic kada i kako da zaposlite prvog marketing menadzera bez skupih gresaka: signali, scorecard, 30-60-90 plan i sta meriti odmah.",
    "date": "2026-03-10",
    "category": "Marketing",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "koliko-brzo-google-ads-donosi-prve-klijente-srbija-2026",
    "title": "Koliko brzo Google Ads donosi prve klijente u Srbiji 2026: realni rokovi i sta meriti",
    "excerpt": "Ako tek krecete sa Google oglasima, najvece pitanje je kada stizu prvi ozbiljni leadovi. Evo realnog 7/30/90 plana, sta usporava rezultat i kako da izbegnete bacanje budzeta.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "8 min",
    "isDraft": false
  },
  {
    "slug": "youtube-reklame-cena-srbija-2026",
    "title": "YouTube reklame cena u Srbiji 2026: budzet, CPV/CPC rasponi i kada se isplate",
    "excerpt": "Koliko kostaju YouTube oglasi u Srbiji 2026, koji test budzet ima smisla i kako da meris da li video kampanje donose profit ili samo preglede bez prodaje.",
    "date": "2026-03-12",
    "category": "Video Marketing",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-restorane-cena-rezervacije-srbija-2026",
    "title": "Google Ads za restorane u Srbiji 2026: cena rezervacije i budzet koji puni stolove",
    "excerpt": "Koliko realno kosta Google Ads za restorane u Srbiji 2026, koji budzet ima smisla po fazama i kako da merite cenu rezervacije, a ne samo cenu klika.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-restorane-cena-srbija-2026",
    "title": "SEO za restorane u Srbiji 2026: cena, lokalni SEO i kako do vise rezervacija",
    "excerpt": "Koliko kosta SEO za restorane u Srbiji 2026, sta realno donosi lokalni SEO za ugostiteljstvo i kako da merite rezultat kroz rezervacije i posete, a ne kroz pozicije.",
    "date": "2026-03-17",
    "category": "Lokalni SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "vodjenje-google-ads-kampanja-fee-izbor-partnera-srbija-2026",
    "title": "Vodjenje Google Ads kampanja cena u Srbiji 2026: sta ulazi u fee i kako da izaberes partnera",
    "excerpt": "Koliko realno kosta vodjenje Google Ads kampanja u Srbiji 2026, kada je fiksni fee bolji od procenta budzeta i kako da procenis da li agencija pravi profit ili samo trosi klikove.",
    "date": "2026-03-12",
    "category": "Google Ads",
    "readTime": "9 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-arhitektonske-biroe-cena-upita-srbija-2026",
    "title": "Google Ads za arhitektonske biroe u Srbiji 2026: cena upita, budzet i kvalitet lead-a",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za arhitektonske biroe u Srbiji 2026, koji budzet ima smisla po fazama i kako da povecas broj ozbiljnih upita za projekte.",
    "date": "2026-03-13",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "kako-odrediti-budzet-za-google-reklame-srbija-2026",
    "title": "Kako odrediti budzet za Google reklame u Srbiji 2026: praktican model pre prvog evra",
    "excerpt": "Korak-po-korak model kako da izracunate realan Google Ads budzet u Srbiji 2026, od maksimalnog CPL-a do test faze i skaliranja bez rasipanja para.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "linkedin-reklame-cena-srbija-2026",
    "title": "LinkedIn reklame cena u Srbiji 2026: realni CPL rasponi, budzet i kada se isplate",
    "excerpt": "Koliko kostaju LinkedIn reklame u Srbiji 2026, koji budzet ima smisla za B2B lead gen i kako da procenis da li kanal donosi pipeline ili samo skupe klikove.",
    "date": "2026-03-14",
    "category": "LinkedIn Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-auto-placeve-cena-leada-srbija-2026",
    "title": "Google Ads za auto placeve u Srbiji 2026: cena lead-a, budzet i vise ozbiljnih kupaca",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za auto placeve u Srbiji 2026, koji budzet ima smisla po fazama i kako da smanjite cenu ozbiljnog upita bez praznih poziva.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-stamparije-cena-leada-srbija-2026",
    "title": "Google Ads za stamparije u Srbiji 2026: cena lead-a, budzet i vise profitabilnih B2B upita",
    "excerpt": "Koliko realno kostaju Google Ads kampanje za stamparije u Srbiji 2026, koji budzet ima smisla i kako da smanjite cenu kvalitetnog upita bez praznih poziva i neisplativih poslova.",
    "date": "2026-03-14",
    "category": "Google Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "landing-stranica-za-google-ads-cena-srbija-2026",
    "title": "Landing stranica za Google Ads: cena u Srbiji 2026, rokovi i sta stvarno ulazi",
    "excerpt": "Koliko realno kosta landing stranica za Google Ads u Srbiji 2026, koji su tipicni rasponi po fazama i sta mora da postoji da klikovi postanu upiti i prodaja.",
    "date": "2026-03-14",
    "category": "Web Design",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-budzet-kalkulator-cpa-srbija-2026",
    "title": "Google Ads budzet kalkulator Srbija 2026: kako da postavis CPA granicu pre trosenja novca",
    "excerpt": "Praktican vodic za firme u Srbiji: kako da izracunas realan Google Ads budzet, postavis maksimalni CPA i izbegnes trosenje novca na klikove koji ne donose profit.",
    "date": "2026-03-15",
    "category": "Google Ads",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "instagram-marketing-za-frizerske-salone-srbija-2026",
    "title": "Instagram marketing za frizerske salone u Srbiji 2026: kako popuniti termine",
    "excerpt": "Praktican vodic za vlasnike salona: koji Instagram format donosi zakazivanja, koliki budzet ima smisla i kako meriti da li vam marketing zaista puni stolice.",
    "date": "2026-03-17",
    "category": "Drustvene Mreze",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "google-ads-za-frizerske-salone-cena-srbija-2026",
    "title": "Google Ads za frizerske salone u Srbiji 2026: cena termina, budzet i strategija",
    "excerpt": "Koliko kostaju Google reklame za frizerske salone u Srbiji 2026, koji budzet ima smisla i kako da dovedete klijente koji vec traze vas tip usluge.",
    "date": "2026-03-17",
    "category": "Marketing",
    "readTime": 9,
    "isDraft": false
  },
  {
    "slug": "seo-za-frizerske-salone-cena-srbija-2026",
    "title": "SEO za frizerske salone u Srbiji 2026: cena, lokalni SEO i kako do vise termina",
    "excerpt": "Koliko kosta SEO za frizerski salon u Srbiji 2026, zasto lokalni SEO dominira kod salona i kako da merite rezultat kroz zakazane termine.",
    "date": "2026-03-17",
    "category": "Lokalni SEO",
    "readTime": "11 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-kozmeticke-salone-cena-srbija-2026",
    "title": "SEO za kozmeticke salone u Srbiji 2026: cena, lokalni SEO i kako do vise termina",
    "excerpt": "Koliko kosta SEO za kozmeticke salone u Srbiji 2026, zasto lokalni SEO presuduje i kako da merite rezultat kroz zakazane termine, ne kroz pozicije.",
    "date": "2026-03-17",
    "category": "Lokalni SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-teretane-cena-upisa-srbija-2026",
    "title": "Instagram reklame za teretane u Srbiji 2026: cena upisa, budzet i kako popuniti salu",
    "excerpt": "Koliko kostaju Instagram reklame za teretane i fitnes studije u Srbiji 2026, koji budzet ima smisla i kako da dovedete clanove koji zapravo ostaju duze od januara.",
    "date": "2026-03-17",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "instagram-reklame-za-racunovodje-cena-klijenta-srbija-2026",
    "title": "Instagram reklame za racunovodje u Srbiji 2026: koliko kosta novi klijent i sta zapravo radi",
    "excerpt": "Koliko kostaju Instagram reklame za racunovodstvene agencije u Srbiji 2026, koji tipovi kampanja donose klijente i kako da ne bacite budzet na pogresan format.",
    "date": "2026-03-17",
    "category": "Instagram Ads",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-racunovodje-cena-srbija-2026",
    "title": "SEO za racunovodje u Srbiji 2026: cena, lokalni SEO i kako do vise klijenata",
    "excerpt": "Koliko realno kosta SEO za racunovodstvene agencije u Srbiji 2026, sta ulazi u cenu i kako da merite rezultat kroz nove klijente umesto praznog saobracaja.",
    "date": "2026-03-17",
    "category": "Lokalni SEO",
    "readTime": "10 min",
    "isDraft": false
  },
  {
    "slug": "seo-za-stomatologe-cena-srbija-2026",
    "title": "SEO za stomatologe u Srbiji 2026: cena, lokalni SEO i kako do vise pacijenata",
    "excerpt": "Koliko realno kosta SEO za stomatolosku ordinaciju u Srbiji 2026, sta donosi lokalni SEO za stomatologe i kako da merite rezultat kroz zakazane termine, a ne kroz pozicije.",
    "date": "2026-03-17",
    "category": "Lokalni SEO",
    "readTime": "11 min",
    "isDraft": false
  }
]
