/**
 * Page meta data — lazy loaded to keep index bundle small.
 * Contains pageMeta, pageSchemas, orgSchema, websiteSchema, setJsonLd
 */
const SITE_URL = 'https://platinumzenith.com'

export const pageMeta = {
  '/': {
    title: 'Platinum Zenith | Digitalna Agencija | Marketing, Web Design, Consulting',
    description: 'Digitalna agencija iz Zrenjanina. Izrada sajtova, SEO, Google Ads, društvene mreže. Revenue share model — zarađujemo kad vi zarađujete. Besplatna procena.',
    keywords: 'digitalna agencija, marketing agencija, web design, Zrenjanin, Srbija, digitalni marketing, izrada sajta',
  },
  '/web-design': {
    title: 'Web Design & Izrada Sajta | Platinum Zenith',
    description: 'Sajtovi koji pretvaraju posetioce u klijente uz mobile-first UX, PageSpeed 95+ i strukturu koja podiže upite, prodaju i dugoročnu SEO vidljivost.',
    keywords: 'web dizajn, izrada sajta, web development, WordPress, React, responsive dizajn, sajt koji prodaje',
  },
  '/digitalni-marketing': {
    title: 'Digitalni Marketing | Zenith Sistem | Platinum Zenith',
    description: 'Meta Ads, Google Ads i TikTok Ads kampanje sa jasnim KPI-jevima, optimizacijom budžeta i sistemom koji donosi predvidljivu akviziciju klijenata.',
    keywords: 'digitalni marketing, Meta Ads, Google Ads, TikTok Ads, ROAS, PPC, online oglašavanje',
  },
  '/consulting': {
    title: 'Poslovno Savetovanje | Platinum Zenith',
    description: 'Biznis konsultacije za vlasnike firmi: audit, strategija rasta i implementacija kroz jasne akcione korake koji uklanjaju uska grla i podižu profit.',
    keywords: 'poslovno savetovanje, biznis consulting, strategija rasta, audit, marketinška strategija',
  },
  '/cro': {
    title: 'CRO Optimizacija Konverzije | Platinum Zenith',
    description: 'CRO optimizacija koja diže broj upita i prodaja bez većeg budžeta: heatmap analiza, A/B testovi, UX audit i konkretne iteracije za rast konverzije.',
    keywords: 'CRO, optimizacija konverzije, A/B testiranje, UX audit, heatmap, bounce rate',
  },
  '/kontakt': { title: 'Kontakt | Platinum Zenith', description: 'Kontaktirajte Platinum Zenith i zakažite besplatne konsultacije u Zrenjaninu. Pošaljite upit i dobijte konkretan plan rasta za vaš biznis.', keywords: 'kontakt, konsultacije, Platinum Zenith kontakt, Zrenjanin' },
  '/o-nama': { title: 'O Nama | Platinum Zenith', description: 'Upoznajte Platinum Zenith tim iz Zrenjanina: digitalni marketing, web design i consulting fokusiran na profitabilan rast i merljive rezultate.', keywords: 'o nama, Platinum Zenith, digitalna agencija Zrenjanin, tim, misija' },
  '/case-studies': { title: 'Case Studies | Rezultati | Platinum Zenith', description: 'Studije slučaja sa realnim rezultatima klijenata: rast prihoda, niži trošak po kupovini i bolji ROI kroz digitalni marketing, web sajt i CRO optimizaciju.', keywords: 'case studies, rezultati, portfolio, referentni projekti, ROI' },
  '/paketi': { title: 'Paketi & Cene | Platinum Zenith', description: 'Paketi i cene za digitalni marketing i web usluge: Starter od 499€, Growth od 1.499€ i Enterprise po meri, bez skrivenih troškova i uz revenue share opciju.', keywords: 'cene, paketi, pricing, Starter, Growth, Enterprise' },
  '/uslovi-koriscenja': { title: 'Uslovi Korišćenja | Platinum Zenith', description: 'Pročitajte uslove korišćenja Platinum Zenith usluga, prava i obaveze korisnika, način saradnje, plaćanja i ograničenja odgovornosti.', keywords: 'uslovi korišćenja, terms of service' },
  '/uslovi-kupovine': { title: 'Uslovi Kupovine | Platinum Zenith', description: 'Uslovi kupovine za Platinum Zenith: ugovaranje putem email korespondencije, B2B model saradnje, reklamacije, isporuka i pravila realizacije.', keywords: 'uslovi kupovine, B2B kupovina, ugovaranje emailom, reklamacije' },
  '/nacin-placanja': { title: 'Način Plaćanja | Platinum Zenith', description: 'Način plaćanja za Platinum Zenith: virmansko plaćanje za pravna lica i izdavanje fakture nakon sklopljenog dogovora putem emaila.', keywords: 'način plaćanja, virman, pravna lica, faktura, B2B' },
  '/dostava': { title: 'Dostava | Platinum Zenith', description: 'Uslovi dostave i realizacije: isporuka nakon potvrđenog dogovora, rokovi, troškovi i proces za fizičku robu i digitalne usluge.', keywords: 'dostava, isporuka, rokovi, digitalne usluge, fizička roba' },
  '/politika-privatnosti': { title: 'Politika Privatnosti | Platinum Zenith', description: 'Politika privatnosti Platinum Zenith agencije: kako prikupljamo, obrađujemo i štitimo lične podatke, koja su vaša prava i kako ostvarujete GDPR zaštitu.', keywords: 'politika privatnosti, privacy policy, GDPR' },
  '/drustvene-mreze': { title: 'Društvene Mreže | Instagram, Facebook, TikTok, LinkedIn | Platinum Zenith', description: 'Instagram, Facebook, TikTok i LinkedIn strategije za firme u Srbiji: content, community i plaćene kampanje koje podižu engagement, upite i prodaju.', keywords: 'društvene mreže, Instagram marketing, Facebook, TikTok, LinkedIn, SMM' },
  '/faq': { title: 'Česta Pitanja (FAQ) | Platinum Zenith', description: 'Česta pitanja o saradnji sa Platinum Zenith agencijom: proces rada, cene, rokovi, komunikacija, izveštavanje i merljivi rezultati.', keywords: 'FAQ, česta pitanja' },
  '/blog': { title: 'Blog | Marketing Saveti i Strategije | Platinum Zenith', description: 'Blog o digitalnom marketingu, prodaji i rastu biznisa: praktične strategije, studije slučaja, SEO i Meta/Google Ads saveti.', keywords: 'blog, marketing saveti, digitalni marketing blog' },
  '/industrije/e-commerce': { title: 'E-Commerce Marketing | Platinum Zenith', description: 'Kompletni marketing sistemi za e-commerce brendove u Srbiji: Meta Ads, Google Ads, email automatizacija, CRO optimizacija i retargeting. Merljiv ROAS.', keywords: 'e-commerce marketing, online prodavnica, ROAS' },
  '/industrije/saas': { title: 'SaaS Marketing | Platinum Zenith', description: 'SaaS marketing strategije za brži MRR rast: akvizicija korisnika, onboarding, aktivacija, retencija i smanjenje churn-a kroz merljiv full-funnel pristup.', keywords: 'SaaS marketing, MRR rast, B2B marketing' },
  '/industrije/lokalni-biznisi': { title: 'Marketing za Lokalne Biznise | Platinum Zenith', description: 'Marketing za lokalne biznise u Srbiji: Google Business optimizacija, lokalni SEO, Meta i Google oglasi koji povećavaju pozive, upite i rezervacije.', keywords: 'lokalni marketing, lokalni SEO, Google Business' },
  '/marketing-agencija-beograd': { title: 'Marketing Agencija za Beograd | Digitalni Marketing | Platinum Zenith', description: 'Digitalni marketing za firme u Beogradu: izrada sajtova, SEO, Google Ads i društvene mreže uz jasne KPI ciljeve, mesečne izveštaje i plan rasta po budžetu.', keywords: 'marketing agencija beograd, digitalni marketing beograd, seo beograd, izrada sajta beograd, google ads beograd' },
  '/seo-optimizacija-cena': { title: 'Koliko Košta SEO Optimizacija u Srbiji 2026 | Cene SEO | Platinum Zenith', description: 'Realne cene SEO optimizacije u Srbiji: osnovni paketi od 300€, napredni od 500€ i premium od 1.200€ mesečno, uz audit sajta i plan rasta pozicija.', keywords: 'seo optimizacija cena, koliko košta seo, seo cena srbija, seo agencija cena, cena seo optimizacije' },
  '/marketing-agencija-zrenjanin': { title: 'Marketing Agencija Zrenjanin | Digitalni Marketing | Platinum Zenith', description: 'Digitalni marketing u Zrenjaninu. Izrada sajtova, SEO, Google Ads, društvene mreže. Lokalna agencija koja donosi rezultate.', keywords: 'marketing agencija zrenjanin, digitalni marketing zrenjanin, izrada sajta zrenjanin, seo zrenjanin, web dizajn zrenjanin' },
  '/cene-izrade-sajta': { title: 'Koliko Košta Izrada Sajta u Srbiji 2026 | Cene i Vodič | Platinum Zenith', description: 'Realne cene izrade sajta u Srbiji za 2026. godinu. Prezentacioni sajt od 300€, poslovni od 800€, web shop od 1.500€. Bez skrivenih troškova.', keywords: 'cena izrade sajta, koliko košta sajt, izrada sajta cena, web dizajn cena, izrada sajta srbija, cena web sajta' },
  '/agencija-vs-freelancer': { title: 'Agencija ili Freelancer? Uporedni Vodič za 2026 | Platinum Zenith', description: 'Agencija vs freelancer: poređenje cene, kvaliteta, rokova i pouzdanosti za firme u Srbiji koje biraju partnera za izradu sajta, SEO ili digitalni marketing.', keywords: 'agencija vs freelancer, agencija ili freelancer, izrada sajta agencija, freelancer sajt, marketing agencija srbija, freelancer vs agencija cena' },
  '/cene-digitalnog-marketinga': { title: 'Koliko Košta Digitalni Marketing u Srbiji 2026 | Cene i Vodič | Platinum Zenith', description: 'Realne cene digitalnog marketinga u Srbiji za 2026. Mesečni paketi od 300€, SEO od 200€, Google Ads upravljanje od 200€. Pregled troškova po usluzi.', keywords: 'cena digitalnog marketinga, koliko košta marketing, marketing agencija cena, SEO cena, Google Ads cena, Facebook Ads cena, digitalni marketing srbija' },
  '/marketing-agencija-novi-sad': { title: 'Marketing Agencija Novi Sad | Digitalni Marketing | Platinum Zenith', description: 'Marketing agencija za firme u Novom Sadu. Izrada sajtova, SEO, Google Ads, društvene mreže. Besplatna procena i merljivi rezultati.', keywords: 'marketing agencija novi sad, digitalni marketing novi sad, SEO novi sad, izrada sajta novi sad, google ads novi sad, marketing vojvodina' },
  '/web-shop-nema-prodaju': { title: 'Web Shop Nema Prodaju? 5 Razloga i Rešenja | Platinum Zenith', description: 'Vaš web shop ima posete, ali nema prodaju? Otkrivamo 5 najčešćih razloga, konkretna rešenja za svaki problem i korake za brže podizanje konverzije.', keywords: 'web shop nema prodaju, zašto web shop ne prodaje, online prodavnica bez prodaje, e-commerce konverzija, web shop optimizacija, checkout optimizacija' },
  '/koliko-kosta-facebook-reklama': { title: 'Koliko Košta Facebook Reklama u Srbiji 2026 | Vodič Kroz Cene | Platinum Zenith', description: 'Realne cene Facebook i Instagram oglasa u Srbiji za 2026. CPC od 0,05€, mesečni budžet od 200€. Koliko plaćate Meti, koliko agenciji i šta da očekujete.', keywords: 'koliko košta facebook reklama, facebook oglasi cena, instagram oglasi cena srbija, facebook ads srbija, cena oglašavanja na facebooku, meta ads cena' },
  '/google-reklame-cena': { title: 'Koliko Koštaju Google Reklame u Srbiji 2026 | Vodič Kroz Cene | Platinum Zenith', description: 'Realne cene Google oglasa u Srbiji za 2026. CPC, budžeti po fazama rasta, trošak po leadu i najčešće greške koje povećavaju potrošnju bez rezultata.', keywords: 'google reklame cena, google ads cena, koliko kostaju google reklame, cena po kliku google, google oglasi srbija, upravljanje google ads kampanjama' },
  '/instagram-reklame-cena': { title: 'Koliko Koštaju Instagram Reklame u Srbiji 2026 | Vodič Kroz Cene | Platinum Zenith', description: 'Realne cene Instagram oglasa u Srbiji za 2026. CPC, CPM, budžeti po fazama rasta i najčešće greške koje povećavaju trošak bez više prodaje.', keywords: 'instagram reklame cena, instagram ads cena, koliko kostaju instagram reklame, cena instagram oglasa, instagram oglasavanje srbija, meta ads cena' },
  '/izrada-wordpress-sajta-cena': { title: 'Koliko Košta Izrada WordPress Sajta u Srbiji 2026 | Vodič Kroz Cene | Platinum Zenith', description: 'Cena izrade WordPress sajta u Srbiji 2026: trošak prezentacionog sajta i WooCommerce shopa, šta ulazi u cenu, rokovi i kako da izbegnete skrivene troškove.', keywords: 'izrada wordpress sajta cena, wordpress sajt cena, koliko kosta wordpress sajt, wordpress izrada sajta srbija, woocommerce cena izrade, odrzavanje wordpress sajta' },
  '/marketing-za-advokate': { title: 'Marketing za Advokate | Digitalni Marketing za Advokatske Kancelarije | Platinum Zenith', description: 'Marketing za advokatske kancelarije u Srbiji. SEO, Google Ads, sajt i content marketing. Dovodimo 10-20 kvalifikovanih upita mesečno. ROI 8-12x.', keywords: 'marketing za advokate, digitalni marketing advokatska kancelarija, google ads advokat, seo za advokate, sajt za advokatsku kancelariju, marketing pravne usluge' },
  '/marketing-za-stomatologe': { title: 'Marketing za Stomatologe | Digitalni Marketing za Stomatološke Ordinacije | Platinum Zenith', description: 'Specijalizovani marketing za stomatološke ordinacije u Srbiji. Google Ads, lokalni SEO, sajt i društvene mreže. Dovodimo 15-25 novih pacijenata mesečno.', keywords: 'marketing za stomatologe, digitalni marketing stomatologija, google ads stomatolog, seo za stomatologe, sajt za ordinaciju, marketing stomatološka ordinacija' },
  '/marketing-za-restorane': { title: 'Marketing za Restorane | Digitalni Marketing za Ugostiteljstvo | Platinum Zenith', description: 'Marketing za restorane u Srbiji: Google Business, društvene mreže, plaćeni oglasi i izrada sajta koji povećavaju rezervacije i pune stolove i radnim danima.', keywords: 'marketing za restorane, digitalni marketing ugostiteljstvo, restoran marketing srbija, google business restoran, instagram za restorane, sajt za restoran' },
  '/draft/netokracija-cro-case': { title: 'DRAFT: Kako smo povećali profit 4x kroz CRO izmene | Platinum Zenith', description: 'Interni draft case study članka za Netokraciju: kako su brzina sajta, mini-korpa, order bumps i Niwa AI logika podigli konverziju i profit.', keywords: 'cro case study, netokracija draft, e-commerce konverzija, pagespeed optimizacija, niwa ai, order bumps' },
  '/in-house-tim-vs-agencija': { title: 'In-House Tim ili Marketing Agencija? Uporedni Vodič 2026 | Platinum Zenith', description: 'Zaposliti marketara ili angažovati agenciju? Uporedni vodič sa konkretnim cenama u Srbiji, prednostima i manama oba pristupa. Saznajte šta se više isplati.', keywords: 'in-house marketing vs agencija, zaposliti marketara, marketing agencija ili zaposleni, cena marketing tima srbija, in-house tim vs outsourcing' },
  '/fiksna-naknada-vs-revenue-share': { title: 'Fiksna Naknada vs Revenue Share | Koji Model Naplate je Bolji? | Platinum Zenith', description: 'Uporedni vodič za firme u Srbiji: fiksna mesečna naknada ili revenue share model naplate agencije. Prednosti, mane, primeri iz prakse i saveti za izbor.', keywords: 'fiksna naknada vs revenue share, model naplate agencija, revenue share marketing, kako platiti agenciju, marketing agencija cena model' },
  '/facebook-oglasi-ne-rade': { title: 'Facebook Oglasi Ne Rade? 6 Razloga i Kako Popraviti | Platinum Zenith', description: 'Zašto vaši Facebook oglasi ne donose rezultate i šta konkretno da promenite. Dijagnostika najčešćih grešaka sa koracima za popravku. Besplatna analiza kampanje.', keywords: 'facebook oglasi ne rade, facebook ads ne rade, zašto ne rade facebook oglasi, facebook reklame ne funkcionišu, problemi sa facebook oglasima, facebook kampanja ne daje rezultate' },
  '/alati/roi-kalkulator': { title: 'ROI Kalkulator za Marketing | Besplatan Alat | Platinum Zenith', description: 'Izračunajte povrat investicije za marketing budžet uz besplatan ROI kalkulator, benchmarkove po industriji i brzu procenu koliko kampanje zaista donose profita.', keywords: 'ROI kalkulator, povrat investicije, marketing ROI, marketing budžet, kalkulator profita' },
  '/industrije/startapovi': { title: 'Marketing za Startapove | Platinum Zenith', description: 'Marketing za startapove u Srbiji: validacija ideje, akvizicija prvih korisnika, testiranje ponude i ubrzanje product-market fit-a kroz merljiv growth pristup.', keywords: 'startup marketing, growth hacking' },
}

export const orgSchema = {
  "@context": "https://schema.org", "@type": "Organization", "@id": `${SITE_URL}#organization`, "name": "Platinum Zenith", "url": SITE_URL,
  "logo": `${SITE_URL}/pz-logo.svg`,
  "address": { "@type": "PostalAddress", "streetAddress": "Ruže Šulman 19", "addressLocality": "Zrenjanin", "addressCountry": "RS" },
  "contactPoint": { "@type": "ContactPoint", "email": "aleksandar@platinumzenith.com", "contactType": "customer service", "availableLanguage": ["Serbian", "English"] },
  "sameAs": []
}

export const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "@id": `${SITE_URL}#localbusiness`,
  "name": "Platinum Zenith",
  "url": SITE_URL,
  "image": `${SITE_URL}/og-image.jpg`,
  "telephone": "+381668168929",
  "email": "aleksandar@platinumzenith.com",
  "priceRange": "€€",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "Ruže Šulman 19",
    "addressLocality": "Zrenjanin",
    "postalCode": "23000",
    "addressCountry": "RS"
  },
  "geo": { "@type": "GeoCoordinates", "latitude": 45.3836, "longitude": 20.3819 },
  "areaServed": { "@type": "Country", "name": "Srbija" },
  "parentOrganization": { "@id": `${SITE_URL}#organization` },
  "openingHoursSpecification": [{
    "@type": "OpeningHoursSpecification",
    "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "opens": "09:00",
    "closes": "18:00"
  }]
}

export const websiteSchema = {
  "@context": "https://schema.org", "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL,
  "potentialAction": { "@type": "SearchAction", "target": `${SITE_URL}/?s={search_term_string}`, "query-input": "required name=search_term_string" }
}

export const pageSchemas = {
  '/web-design': { "@context": "https://schema.org", "@type": "Service", "name": "Web Design & Izrada Sajta", "description": "Izrada sajtova sa fokusom na brzinu, UX i konverzije: od strukture stranica do tehničke SEO optimizacije.", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Web Design", "areaServed": { "@type": "Country", "name": "Srbija" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "Web design usluge", "itemListElement": [ { "@type": "Offer", "name": "Prezentacioni sajt", "description": "Brz i SEO-pripremljen sajt za usluge" }, { "@type": "Offer", "name": "Poslovni sajt", "description": "Struktura za upite, lead forme i tracking" }, { "@type": "Offer", "name": "Web shop", "description": "E-commerce sa optimizovanim checkout tokom" } ] } },
  '/digitalni-marketing': { "@context": "https://schema.org", "@type": "Service", "name": "Digitalni Marketing", "description": "Digitalni marketing kroz Meta, Google i TikTok kampanje sa jasnim KPI ciljevima, optimizacijom budžeta i planom skaliranja.", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Digital Marketing", "areaServed": { "@type": "Country", "name": "Srbija" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "Digital marketing usluge", "itemListElement": [ { "@type": "Offer", "name": "Meta Ads", "description": "Akvizicija i retargeting kroz Facebook i Instagram" }, { "@type": "Offer", "name": "Google Ads", "description": "Search, Display i Performance Max kampanje" }, { "@type": "Offer", "name": "TikTok Ads", "description": "Kampanje za awareness i performance" } ] } },
  '/consulting': { "@context": "https://schema.org", "@type": "Service", "name": "Poslovno Savetovanje", "description": "Poslovno savetovanje za vlasnike firmi: audit trenutnog stanja, plan rasta i implementacija kroz jasne akcione korake.", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Business Consulting", "areaServed": { "@type": "Country", "name": "Srbija" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "Consulting programi", "itemListElement": [ { "@type": "Offer", "name": "Biznis audit", "description": "Analiza uskih grla i prioriteta za rast" }, { "@type": "Offer", "name": "Strategija rasta", "description": "Plan akvizicije, ponude i pozicioniranja" }, { "@type": "Offer", "name": "Implementacija", "description": "Operativna podrška u sprovođenju plana" } ] } },
  '/cro': { "@context": "https://schema.org", "@type": "Service", "name": "CRO Optimizacija", "description": "CRO optimizacija koja povećava broj upita i prodaja kroz analizu ponašanja korisnika, A/B testove i UX poboljšanja.", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Conversion Rate Optimization", "areaServed": { "@type": "Country", "name": "Srbija" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "CRO usluge", "itemListElement": [ { "@type": "Offer", "name": "CRO audit", "description": "Analiza toka korisnika i tačaka odustajanja" }, { "@type": "Offer", "name": "A/B test iteracije", "description": "Testiranje varijanti CTA, forme i ponude" }, { "@type": "Offer", "name": "UX optimizacija", "description": "Poboljšanja stranica za veći procenat konverzije" } ] } },
  '/drustvene-mreze': { "@context": "https://schema.org", "@type": "Service", "name": "Upravljanje Društvenim Mrežama", "description": "Instagram, Facebook, TikTok i LinkedIn upravljanje za rast upita, zajednice i prodaje kroz sadržaj i plaćene kampanje.", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Social Media Management", "areaServed": { "@type": "Country", "name": "Srbija" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "SMM usluge", "itemListElement": [ { "@type": "Offer", "name": "Content plan", "description": "Plan sadržaja po kanalu i cilju" }, { "@type": "Offer", "name": "Community management", "description": "Moderacija i odgovori na poruke i komentare" }, { "@type": "Offer", "name": "Plaćene kampanje", "description": "Meta i TikTok oglasi za akviziciju i retargeting" } ] } },
  '/paketi': { "@context": "https://schema.org", "@type": "OfferCatalog", "name": "Platinum Zenith Paketi", "itemListElement": [
    { "@type": "Offer", "name": "Starter", "price": "499", "priceCurrency": "EUR" },
    { "@type": "Offer", "name": "Growth", "price": "1499", "priceCurrency": "EUR" },
    { "@type": "Offer", "name": "Enterprise", "description": "Custom" }
  ]},
  '/uslovi-koriscenja': { "@context": "https://schema.org", "@type": "WebPage", "name": "Uslovi korišćenja", "url": `${SITE_URL}/uslovi-koriscenja`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/politika-privatnosti': { "@context": "https://schema.org", "@type": "WebPage", "name": "Politika privatnosti", "url": `${SITE_URL}/politika-privatnosti`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/uslovi-kupovine': { "@context": "https://schema.org", "@type": "WebPage", "name": "Uslovi kupovine", "url": `${SITE_URL}/uslovi-kupovine`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/nacin-placanja': { "@context": "https://schema.org", "@type": "WebPage", "name": "Način plaćanja", "url": `${SITE_URL}/nacin-placanja`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/dostava': { "@context": "https://schema.org", "@type": "WebPage", "name": "Dostava", "url": `${SITE_URL}/dostava`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/industrije/e-commerce': { "@context": "https://schema.org", "@type": "Service", "name": "E-Commerce Marketing", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "E-Commerce Marketing", "areaServed": "RS" },
  '/industrije/saas': { "@context": "https://schema.org", "@type": "Service", "name": "SaaS Marketing", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "SaaS Marketing", "areaServed": "RS" },
  '/industrije/lokalni-biznisi': { "@context": "https://schema.org", "@type": "Service", "name": "Marketing za Lokalne Biznise", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Local Business Marketing", "areaServed": "RS" },
  '/industrije/startapovi': { "@context": "https://schema.org", "@type": "Service", "name": "Marketing za Startapove", "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "serviceType": "Startup Marketing", "areaServed": "RS" },
  '/agencija-vs-freelancer': { "@context": "https://schema.org", "@type": "WebPage", "name": "Agencija ili freelancer — uporedni vodič", "url": `${SITE_URL}/agencija-vs-freelancer`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/cene-digitalnog-marketinga': { "@context": "https://schema.org", "@type": "WebPage", "name": "Cene digitalnog marketinga u Srbiji 2026", "url": `${SITE_URL}/cene-digitalnog-marketinga`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/marketing-agencija-zrenjanin': { "@context": "https://schema.org", "@type": "ProfessionalService", "name": "Platinum Zenith - Marketing Agencija Zrenjanin", "url": `${SITE_URL}/marketing-agencija-zrenjanin`, "areaServed": { "@type": "City", "name": "Zrenjanin" }, "serviceType": "Digital Marketing" },
  '/marketing-agencija-beograd': { "@context": "https://schema.org", "@type": "ProfessionalService", "name": "Platinum Zenith - Marketing Agencija Beograd", "url": `${SITE_URL}/marketing-agencija-beograd`, "areaServed": { "@type": "City", "name": "Beograd" }, "serviceType": "Digital Marketing" },
  '/marketing-agencija-novi-sad': { "@context": "https://schema.org", "@type": "ProfessionalService", "name": "Platinum Zenith - Marketing Agencija Novi Sad", "url": `${SITE_URL}/marketing-agencija-novi-sad`, "areaServed": { "@type": "City", "name": "Novi Sad" }, "serviceType": "Digital Marketing" },
  '/web-shop-nema-prodaju': { "@context": "https://schema.org", "@type": "WebPage", "name": "Web shop nema prodaju — 5 razloga i rešenja", "url": `${SITE_URL}/web-shop-nema-prodaju`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/koliko-kosta-facebook-reklama': { "@context": "https://schema.org", "@type": "WebPage", "name": "Koliko košta Facebook reklama u Srbiji 2026", "url": `${SITE_URL}/koliko-kosta-facebook-reklama`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/google-reklame-cena': { "@context": "https://schema.org", "@type": "Service", "name": "Google Ads upravljanje kampanjama", "description": "Google Ads upravljanje sa jasnim budžetskim fazama, optimizacijom troška po leadu i fokusom na profitabilan rast.", "serviceType": "Google Ads management", "url": `${SITE_URL}/google-reklame-cena`, "areaServed": { "@type": "Country", "name": "Srbija" }, "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "offers": { "@type": "AggregateOffer", "priceCurrency": "EUR", "lowPrice": "300", "highPrice": "6000", "offerCount": "4" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "Google Ads budžetske faze", "itemListElement": [ { "@type": "Offer", "name": "Početni test", "priceCurrency": "EUR", "price": "300" }, { "@type": "Offer", "name": "Stabilan rast", "priceCurrency": "EUR", "price": "700" }, { "@type": "Offer", "name": "Agresivna akvizicija", "priceCurrency": "EUR", "price": "2000" } ] } },
  '/instagram-reklame-cena': { "@context": "https://schema.org", "@type": "Service", "name": "Instagram Ads upravljanje kampanjama", "description": "Instagram Ads upravljanje sa jasnim budžetskim fazama, optimizacijom CPM/CPC troška i fokusom na kvalitetne upite i prodaju.", "serviceType": "Instagram advertising management", "url": `${SITE_URL}/instagram-reklame-cena`, "areaServed": { "@type": "Country", "name": "Srbija" }, "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "offers": { "@type": "AggregateOffer", "priceCurrency": "EUR", "lowPrice": "200", "highPrice": "5000", "offerCount": "4" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "Instagram Ads budžetske faze", "itemListElement": [ { "@type": "Offer", "name": "Početni test", "priceCurrency": "EUR", "price": "200" }, { "@type": "Offer", "name": "Stabilan rast", "priceCurrency": "EUR", "price": "600" }, { "@type": "Offer", "name": "Skaliranje", "priceCurrency": "EUR", "price": "1500" } ] } },
  '/izrada-wordpress-sajta-cena': { "@context": "https://schema.org", "@type": "Service", "name": "Izrada WordPress sajta", "description": "Izrada WordPress sajta i WooCommerce shopa sa jasnim rasponima cena, rokovima i planom isporuke.", "serviceType": "WordPress web development", "url": `${SITE_URL}/izrada-wordpress-sajta-cena`, "areaServed": { "@type": "Country", "name": "Srbija" }, "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "offers": { "@type": "AggregateOffer", "priceCurrency": "EUR", "lowPrice": "500", "highPrice": "4500", "offerCount": "3" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "WordPress paketi", "itemListElement": [ { "@type": "Offer", "name": "Prezentacioni WordPress sajt", "priceCurrency": "EUR", "price": "500" }, { "@type": "Offer", "name": "Poslovni WordPress sajt", "priceCurrency": "EUR", "price": "1200" }, { "@type": "Offer", "name": "WooCommerce web shop", "priceCurrency": "EUR", "price": "2500" } ] } },
  '/seo-optimizacija-cena': { "@context": "https://schema.org", "@type": "Service", "name": "SEO optimizacija", "description": "SEO optimizacija sa jasnim paketima, tehničkim auditom i planom rasta organskog saobraćaja i upita.", "serviceType": "Search Engine Optimization", "url": `${SITE_URL}/seo-optimizacija-cena`, "areaServed": { "@type": "Country", "name": "Srbija" }, "provider": { "@id": `${SITE_URL}#organization`, "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL }, "offers": { "@type": "AggregateOffer", "priceCurrency": "EUR", "lowPrice": "300", "highPrice": "1200", "offerCount": "3" }, "hasOfferCatalog": { "@type": "OfferCatalog", "name": "SEO paketi", "itemListElement": [ { "@type": "Offer", "name": "Osnovni SEO", "priceCurrency": "EUR", "price": "300" }, { "@type": "Offer", "name": "Napredni SEO", "priceCurrency": "EUR", "price": "500" }, { "@type": "Offer", "name": "Premium SEO", "priceCurrency": "EUR", "price": "1200" } ] } },
  '/draft/netokracija-cro-case': { "@context": "https://schema.org", "@type": "WebPage", "name": "Draft: CRO case study za Netokraciju", "url": `${SITE_URL}/draft/netokracija-cro-case`, "inLanguage": "sr-RS", "isPartOf": { "@type": "WebSite", "name": "Platinum Zenith", "url": SITE_URL } },
  '/alati/roi-kalkulator': { "@context": "https://schema.org", "@type": "SoftwareApplication", "name": "ROI Kalkulator za Marketing", "applicationCategory": "BusinessApplication", "operatingSystem": "Web", "offers": { "@type": "Offer", "price": "0", "priceCurrency": "EUR" }, "description": "Besplatan interaktivni kalkulator za izračunavanje povrata investicije u marketing.", "url": `${SITE_URL}/alati/roi-kalkulator`, "provider": { "@type": "Organization", "name": "Platinum Zenith", "url": SITE_URL } }
}

export function setJsonLd(id, data) {
  let el = document.getElementById(id)
  if (!el) { el = document.createElement('script'); el.id = id; el.type = 'application/ld+json'; document.head.appendChild(el) }
  el.textContent = JSON.stringify(data)
}

export { SITE_URL }
